"""V42C — Curve Projector backed by accountSubscribe state.

Same projection arithmetic as V42B, but the curve baseline is OVERRIDDEN by
the latest accountSubscribe snapshot (vSOL/vTOK) instead of being fetched via
the broker's RPC. This eliminates the RPC round-trip cost on every candidate
firing AND ensures we are projecting on the SAME state the rule fired on.

The "observed delta velocity" piece comes for free: we feed the V42B
projector the `pending_events` synthesized from recent buy-side curve
deltas (vSOL growth converted to SOL).

Inputs:
  broker
  mint_pubkey
  amount_sol
  curve_delta_snap   = CurveAccountSubscriberOracle.snapshot(mint)
  fusion_snap        = optional FeedFusionOracle.snapshot(mint) (may be empty)
  pending_events     = optional list of PendingFlowAtom from shred (may be empty)

Output: same dict shape as project_v42b() plus:
  v42c_baseline_source = "accountSubscribe"
  v42c_baseline_slot   = int
  v42c_baseline_vsol   = int
  v42c_baseline_vtok   = int
  v42c_baseline_age_ms = int

Emits `PGG2-V42C-FLOW-PROJECTION`.
"""
from __future__ import annotations

import os
import time
from dataclasses import dataclass
from typing import Any, Optional, Sequence


LAMPORTS_PER_SOL = 1_000_000_000


def _short(mint: str) -> str:
    if not mint or len(mint) <= 10:
        return mint or "?"
    return mint[:4] + ".." + mint[-4:]


def _env_float(key: str, default: float) -> float:
    try:
        return float(os.environ.get(key, default))
    except (TypeError, ValueError):
        return float(default)


def _now_ms() -> int:
    return int(time.time() * 1000)


def _synthesize_atoms_from_curve_delta(
    curve_delta_snap: dict[str, Any],
    now_ms: int,
) -> list[Any]:
    """Build PendingFlowAtom events from observed curve-delta growth in the
    last 1000ms window. Each lamport of vSOL growth observed is treated as
    'someone bought'. Crude but correct in direction; the V42B projector
    will apply CPMM math on these in time order.
    """
    from pgg2_v42_curve_projector import PendingFlowAtom  # type: ignore

    vsol_d_1000 = int(curve_delta_snap.get("vsol_delta_1000ms", 0))
    if vsol_d_1000 <= 0:
        return []
    sol_amt = max(0.0, float(vsol_d_1000) / LAMPORTS_PER_SOL)
    if sol_amt < 0.0001:
        return []
    # Place the atom at "now - 500ms" so the projector applies it before our
    # hypothetical buy in the projected timeline.
    return [PendingFlowAtom(ts_ms=now_ms - 500, side="buy", sol=sol_amt)]


def project_v42c(
    broker: Any,
    mint_pubkey: str,
    amount_sol: float,
    curve_delta_snap: dict[str, Any],
    fusion_snap: Optional[dict[str, Any]] = None,
    pending_events: Optional[Sequence[Any]] = None,
    logger: Optional[Any] = None,
    tx_fee_sol: Optional[float] = None,
    pnl_floor_sol: float = 0.00060,
    stress_pnl_floor_sol: float = 0.00020,
    stress_latency_ms: int = 500,
) -> dict[str, Any]:
    fusion_snap = fusion_snap or {}
    short = _short(mint_pubkey)
    # Build the projection inputs. We use the V42B projector as the engine,
    # but ATTEMPT to inject the V42C-supplied curve state as the baseline by
    # caching it in a sentinel attribute on the broker for one call.
    try:
        from pgg2_v42b_curve_projector import project_v42b  # type: ignore
        from pgg2_direct_pump import PumpBondingCurve, as_pubkey, pda, PUMP_PROGRAM_ID  # type: ignore
    except Exception as exc:
        return {
            "projection_ok": False,
            "projection_error": f"import:{type(exc).__name__}:{exc}",
            "projected_all_in_pnl": -999.0,
            "projected_pnl_baseline": -999.0,
            "projected_pnl_stress": -999.0,
            "projected_max_loss": -999.0,
            "lead_confidence": 0.0,
            "v42c_baseline_source": "accountSubscribe",
        }
    # Cache the curve override on the broker so its `.bonding_curve()` calls
    # see it. The V42B projector calls broker.bonding_curve(mint_pk) once for
    # the current state; the +500ms stress is generated by re-running
    # project_post_flow_quote, which ALSO calls .bonding_curve(). To avoid
    # mutating the broker globally, we patch a per-call cache key.
    vsol = int(curve_delta_snap.get("virtual_sol_reserves", 0))
    vtok = int(curve_delta_snap.get("virtual_token_reserves", 0))
    rsol = int(curve_delta_snap.get("real_sol_reserves", 0))
    rtok = int(curve_delta_snap.get("real_token_reserves", 0))
    n_points = int(curve_delta_snap.get("n_points", 0))
    baseline_age_ms = int(curve_delta_snap.get("curve_age_ms", 0))
    # If we have NO accountSubscribe state at all, fall back to live broker
    # fetch (V42B behaviour).
    if n_points == 0 or vsol <= 0 or vtok <= 0:
        out = project_v42b(
            broker=broker,
            mint_pubkey=mint_pubkey,
            amount_sol=amount_sol,
            fusion_snap=fusion_snap,
            curve_delta_snap=curve_delta_snap,
            pending_events=list(pending_events or []),
            logger=None,
            tx_fee_sol=tx_fee_sol,
            pnl_floor_sol=pnl_floor_sol,
            stress_pnl_floor_sol=stress_pnl_floor_sol,
            stress_latency_ms=stress_latency_ms,
        )
        out["v42c_baseline_source"] = "broker_rpc_fallback"
        out["v42c_baseline_slot"] = 0
        out["v42c_baseline_vsol"] = 0
        out["v42c_baseline_vtok"] = 0
        out["v42c_baseline_age_ms"] = baseline_age_ms
        if logger is not None:
            try:
                logger(
                    f"PGG2-V42C-FLOW-PROJECTION mint={short} source=broker_rpc_fallback "
                    f"amount_sol={amount_sol:.6f} "
                    f"projected_pnl_baseline={out.get('projected_pnl_baseline', -999.0):+.6f} "
                    f"projected_pnl_stress={out.get('projected_pnl_stress', -999.0):+.6f} "
                    f"projected_max_loss={out.get('projected_max_loss', -999.0):+.6f} "
                    f"lead_confidence={out.get('lead_confidence', 0.0):.3f}"
                )
            except Exception:
                pass
        return out

    # Build a PumpBondingCurve from the snapshot.
    try:
        mint_pk = as_pubkey(mint_pubkey)
        curve_key = pda(PUMP_PROGRAM_ID, b"bonding-curve", bytes(mint_pk))
        override_curve = PumpBondingCurve(
            key=curve_key,
            virtual_token_reserves=vtok,
            virtual_sol_reserves=vsol,
            real_token_reserves=rtok,
            real_sol_reserves=rsol,
            token_total_supply=0,
            complete=False,
            creator=curve_key,
            is_mayhem=False,
            cashback_enabled=False,
        )
    except Exception as exc:
        return {
            "projection_ok": False,
            "projection_error": f"build_override:{type(exc).__name__}:{exc}",
            "projected_all_in_pnl": -999.0,
            "projected_pnl_baseline": -999.0,
            "projected_pnl_stress": -999.0,
            "projected_max_loss": -999.0,
            "lead_confidence": 0.0,
            "v42c_baseline_source": "accountSubscribe",
        }
    # Hot-patch broker.bonding_curve for the duration of this projection.
    orig_bc = broker.bonding_curve
    def _bc_override(_mint_pk: Any, _orig=orig_bc, _ov=override_curve, _expected=mint_pk):
        try:
            if str(_mint_pk) == str(_expected):
                return _ov
        except Exception:
            pass
        return _orig(_mint_pk)
    broker.bonding_curve = _bc_override  # type: ignore[assignment]
    try:
        atoms = list(pending_events or [])
        if not atoms:
            atoms = _synthesize_atoms_from_curve_delta(curve_delta_snap, _now_ms())
        out = project_v42b(
            broker=broker,
            mint_pubkey=mint_pubkey,
            amount_sol=amount_sol,
            fusion_snap=fusion_snap,
            curve_delta_snap=curve_delta_snap,
            pending_events=atoms,
            logger=None,
            tx_fee_sol=tx_fee_sol,
            pnl_floor_sol=pnl_floor_sol,
            stress_pnl_floor_sol=stress_pnl_floor_sol,
            stress_latency_ms=stress_latency_ms,
        )
    finally:
        broker.bonding_curve = orig_bc  # type: ignore[assignment]
    out["v42c_baseline_source"] = "accountSubscribe"
    out["v42c_baseline_slot"] = int(curve_delta_snap.get("last_poll_ts_ms", 0))
    out["v42c_baseline_vsol"] = vsol
    out["v42c_baseline_vtok"] = vtok
    out["v42c_baseline_age_ms"] = baseline_age_ms
    if logger is not None:
        try:
            logger(
                f"PGG2-V42C-FLOW-PROJECTION mint={short} source=accountSubscribe "
                f"amount_sol={amount_sol:.6f} "
                f"projected_pnl_baseline={out.get('projected_pnl_baseline', -999.0):+.6f} "
                f"projected_pnl_stress={out.get('projected_pnl_stress', -999.0):+.6f} "
                f"projected_max_loss={out.get('projected_max_loss', -999.0):+.6f} "
                f"lead_confidence={out.get('lead_confidence', 0.0):.3f} "
                f"streak={int(curve_delta_snap.get('positive_delta_streak', 0))} "
                f"vel={float(curve_delta_snap.get('curve_update_velocity_per_sec', 0.0)):.2f} "
                f"baseline_age_ms={baseline_age_ms}"
            )
        except Exception:
            pass
    return out


__all__ = ["project_v42c"]
