#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# Phase 6 2026-05-08 dry-live wrapper.
# Adds MIN-HOLD floor on top of Phase 5.
# Phase 5 autopsy: every loss exited within 0.7-5.2s before the actual pump
# arrived 5-90s later. 2QzC17Tx exited at 0.71s via quote_loss_clamp for -$0.30,
# then mint ran to 5.47x post-close. Cost-model exits at sub-second are
# structurally broken — they can't know the trade's fate that early.
#
# MIN-HOLD: priced_snap and curve_lag_reveal positions hold for at least 12s,
# only catastrophic dump (mult <= 0.50) or migration closes during the hold.
# The moonshot latch still arms inside the hold, so fast pumps take over with
# the rider's own exits. After 12s, all normal exits resume.

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_phase6_drylive}"

# Phase 2A — adaptive guards + filter pruning
export PGG2_PRICED_SNAP_BLOCK_TOP700=1.01
export PGG2_LIVE_BLOCK_HHI700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE1500_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_PER_BUYER_ABOVE=99999
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_TIGHT=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_BELOW=0
export PGG2_BLOCK_HOURS_UTC="${PGG2_BLOCK_HOURS_UTC:-18,19,20}"
export PGG2_CIRCUIT_BREAKER_LOSSES="${PGG2_CIRCUIT_BREAKER_LOSSES:-5}"
export PGG2_CIRCUIT_BREAKER_PAUSE_SEC="${PGG2_CIRCUIT_BREAKER_PAUSE_SEC:-300}"

# Phase 3 — keep PEAK-LOCK + curve_lag_reveal lane (rides via moonshot logic)
export PGG2_CURVE_LAG_REVEAL_ENABLED="${PGG2_CURVE_LAG_REVEAL_ENABLED:-1}"
export PGG2_PEAK_LOCK_ENABLED="${PGG2_PEAK_LOCK_ENABLED:-1}"
export PGG2_PEAK_LOCK_LOW_PEAK="${PGG2_PEAK_LOCK_LOW_PEAK:-1.18}"
export PGG2_PEAK_LOCK_LOW_FLOOR="${PGG2_PEAK_LOCK_LOW_FLOOR:-1.05}"
export PGG2_PEAK_LOCK_LOW_TRAIL="${PGG2_PEAK_LOCK_LOW_TRAIL:-0.92}"
export PGG2_PEAK_LOCK_MID_PEAK="${PGG2_PEAK_LOCK_MID_PEAK:-1.30}"
export PGG2_PEAK_LOCK_MID_FLOOR="${PGG2_PEAK_LOCK_MID_FLOOR:-1.15}"
export PGG2_PEAK_LOCK_MID_TRAIL="${PGG2_PEAK_LOCK_MID_TRAIL:-0.88}"
export PGG2_PEAK_LOCK_HIGH_PEAK="${PGG2_PEAK_LOCK_HIGH_PEAK:-1.60}"
export PGG2_PEAK_LOCK_HIGH_FLOOR="${PGG2_PEAK_LOCK_HIGH_FLOOR:-1.30}"
export PGG2_PEAK_LOCK_HIGH_TRAIL="${PGG2_PEAK_LOCK_HIGH_TRAIL:-0.85}"
export PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW="${PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW:-1.18}"
export PGG2_ANTI_MARTINGALE_ENABLED="${PGG2_ANTI_MARTINGALE_ENABLED:-1}"
export PGG2_ANTI_MARTINGALE_LOSS_STREAK="${PGG2_ANTI_MARTINGALE_LOSS_STREAK:-2}"
export PGG2_ANTI_MARTINGALE_LOSS_SCALE="${PGG2_ANTI_MARTINGALE_LOSS_SCALE:-0.50}"
export PGG2_ANTI_MARTINGALE_WIN_STREAK="${PGG2_ANTI_MARTINGALE_WIN_STREAK:-2}"
export PGG2_ANTI_MARTINGALE_WIN_SCALE="${PGG2_ANTI_MARTINGALE_WIN_SCALE:-1.30}"

# Phase 4/5 — MOONSHOT-RIDER
export PGG2_MOONSHOT_RIDE_ENABLED="${PGG2_MOONSHOT_RIDE_ENABLED:-1}"
export PGG2_MOONSHOT_RIDE_PEAK="${PGG2_MOONSHOT_RIDE_PEAK:-1.30}"
export PGG2_MOONSHOT_RIDE_WINDOW_SEC="${PGG2_MOONSHOT_RIDE_WINDOW_SEC:-30.0}"
export PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC="${PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC:-120.0}"
export PGG2_MOONSHOT_RIDE_TIER0_TRAIL="${PGG2_MOONSHOT_RIDE_TIER0_TRAIL:-0.85}"
export PGG2_MOONSHOT_RIDE_TIER1_PEAK="${PGG2_MOONSHOT_RIDE_TIER1_PEAK:-1.60}"
export PGG2_MOONSHOT_RIDE_TIER1_TRAIL="${PGG2_MOONSHOT_RIDE_TIER1_TRAIL:-0.80}"
export PGG2_MOONSHOT_RIDE_TIER2_PEAK="${PGG2_MOONSHOT_RIDE_TIER2_PEAK:-2.00}"
export PGG2_MOONSHOT_RIDE_TIER2_TRAIL="${PGG2_MOONSHOT_RIDE_TIER2_TRAIL:-0.60}"
export PGG2_MOONSHOT_RIDE_TIER3_PEAK="${PGG2_MOONSHOT_RIDE_TIER3_PEAK:-3.00}"
export PGG2_MOONSHOT_RIDE_TIER3_TRAIL="${PGG2_MOONSHOT_RIDE_TIER3_TRAIL:-0.40}"
export PGG2_MOONSHOT_RIDE_MIN_HOLD_SEC="${PGG2_MOONSHOT_RIDE_MIN_HOLD_SEC:-5.0}"
export PGG2_MOONSHOT_RIDE_PANIC_TRAIL="${PGG2_MOONSHOT_RIDE_PANIC_TRAIL:-0.30}"

# Phase 5 — hard_break grace (still active for trades that exit min-hold)
export PGG2_HARD_BREAK_GRACE_ENABLED="${PGG2_HARD_BREAK_GRACE_ENABLED:-1}"
export PGG2_HARD_BREAK_GRACE_SEC="${PGG2_HARD_BREAK_GRACE_SEC:-8.0}"
export PGG2_HARD_BREAK_GRACE_BUY_AGE_MS="${PGG2_HARD_BREAK_GRACE_BUY_AGE_MS:-1500}"

# Phase 5 — entry window widening
export PGG2_PRICED_SNAP_MAX_AGE_SEC="${PGG2_PRICED_SNAP_MAX_AGE_SEC:-60.0}"
export PGG2_PRICED_SNAP_MAX_MOVE="${PGG2_PRICED_SNAP_MAX_MOVE:-2.50}"
export PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC="${PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC:-60.0}"

# Phase 6 — MIN-HOLD floor for priced_snap + curve_lag_reveal
export PGG2_MIN_HOLD_ENABLED="${PGG2_MIN_HOLD_ENABLED:-1}"
export PGG2_MIN_HOLD_SEC="${PGG2_MIN_HOLD_SEC:-12.0}"
export PGG2_MIN_HOLD_PANIC_FLOOR="${PGG2_MIN_HOLD_PANIC_FLOOR:-0.50}"

exec ./start_pgg2_direct_drylive_candidate.sh
