#!/usr/bin/env bash
# V51 Stage A launcher: SWQOS entry + V47G watchdog exit + Helius holder pre-veto.
# Hard caps: 1 close target, fee budget 0.00025 SOL, realized drawdown 0.0080 SOL,
# 35min wall clock, max tip 0.000005 SOL.
set -uo pipefail

cd /root/piggy

# -- env file --
if [[ -f /root/piggy/.env ]]; then
  set -a
  # shellcheck disable=SC1091
  source /root/piggy/.env
  set +a
fi

# Refuse to start if already running.
if pgrep -f "pgg2_v51_stagea_live.py" >/dev/null 2>&1; then
  echo "V51-LAUNCH-ABORT pgg2_v51_stagea_live.py already running" >&2
  pgrep -af "pgg2_v51_stagea_live.py" >&2
  exit 12
fi

# ===========================================================================
# V51-SPECIFIC KNOBS
# ===========================================================================
export PGG2_V51_LIVE=1
export PGG2_V51_SWQOS_TIP_SOL="${PGG2_V51_SWQOS_TIP_SOL:-0.000005}"
export PGG2_V51_MAX_TIP_SOL="${PGG2_V51_MAX_TIP_SOL:-0.000005}"
export PGG2_V51_STAGEA_FEE_BUDGET_SOL="${PGG2_V51_STAGEA_FEE_BUDGET_SOL:-0.00025}"
export PGG2_V51_MAX_FAILED_SENDS="${PGG2_V51_MAX_FAILED_SENDS:-2}"
export PGG2_V51_MAX_OPEN="${PGG2_V51_MAX_OPEN:-1}"
export PGG2_V51_MAX_CLOSES="${PGG2_V51_MAX_CLOSES:-1}"
export PGG2_V51_MAX_SECONDS="${PGG2_V51_MAX_SECONDS:-2100}"
export PGG2_V51_MAX_REALIZED_DRAWDOWN_SOL="${PGG2_V51_MAX_REALIZED_DRAWDOWN_SOL:-0.0080}"
export PGG2_V51_EMERGENCY_WALLET_FLOOR_DECREASE_SOL="${PGG2_V51_EMERGENCY_WALLET_FLOOR_DECREASE_SOL:-0.0150}"
export PGG2_V51_MAX_HOLD_MS="${PGG2_V51_MAX_HOLD_MS:-1500}"
export PGG2_V51_PRIORITY_FEE_MICROLAMPORTS="${PGG2_V51_PRIORITY_FEE_MICROLAMPORTS:-100000}"
export PGG2_V51_CU_LIMIT="${PGG2_V51_CU_LIMIT:-200000}"
export PGG2_V51_HOLDER_TTL_S="${PGG2_V51_HOLDER_TTL_S:-30}"
export PGG2_V51_HOLDER_RATE_PER_MIN="${PGG2_V51_HOLDER_RATE_PER_MIN:-60}"
export PGG2_V51_HOLDER_RULES_PATH="${PGG2_V51_HOLDER_RULES_PATH:-/root/piggy/data/v51_holder_quality_rules.json}"
export PGG2_V51_TOKEN2022_WHITELIST="${PGG2_V51_TOKEN2022_WHITELIST:-}"
export PGG2_V51_EMERGENCY_MIN_SOL_FLOOR_SOL="${PGG2_V51_EMERGENCY_MIN_SOL_FLOOR_SOL:-0.0005}"
export PGG2_V51_EMERGENCY_MIN_SOL_RATIO="${PGG2_V51_EMERGENCY_MIN_SOL_RATIO:-0.40}"
export PGG2_V51_INITIAL_SELL_SLIPPAGE_PCT="${PGG2_V51_INITIAL_SELL_SLIPPAGE_PCT:-0.50}"
export PGG2_V51_WALLET_POLL_S="${PGG2_V51_WALLET_POLL_S:-10}"

# V47G watchdog knobs.
export PGG2_V47G_WATCHDOG_INTERVAL_MS="${PGG2_V47G_WATCHDOG_INTERVAL_MS:-250}"
export PGG2_V47G_POSITION_QUOTE_WATCHDOG=1
export PGG2_V47F_MIDHOLD_DUMP_ABORT=1
export PGG2_V47F_HOLD_CAPS=1

# Trade sizing (single 0.005 SOL ticket per entry, 1 close target).
export PGG2_TRADE_SIZE_SOL="${PGG2_TRADE_SIZE_SOL:-0.005}"

# ===========================================================================
# V48 LIVE-SMOKE ENVELOPE
# ===========================================================================
export PGG2_V48_LIVE_SMOKE_ENABLED=1
export PGG2_EXECUTION_MODE=live
export PGG2_ENABLE_LIVE=1
export PIGGY_PAPER_TRADING=0
export PGG2_DRY_LIVE_MODE=0
export PGG2_LIVE_BROKER=direct_pump
export PGG2_WALLET_KEYPAIR="${PGG2_WALLET_KEYPAIR:-/root/piggy/live_wallet.key}"
export PGG2_LIVE_CONFIRM="${PGG2_LIVE_CONFIRM:-I_ACCEPT_REAL_SOL_RISK}"
export PGG2_DIRECT_LIVE_CONFIRM="${PGG2_DIRECT_LIVE_CONFIRM:-I_ACCEPT_DIRECT_PUMP_RISK}"
export PGG2_QUOTE_SHADOW_POSITIONS=0
export PGG2_QUOTE_SIMULATE=0
export PGG2_LIVE_SKIP_PREFLIGHT=1
export PGG2_V48_LIVE_SIMULATE_BUY_BEFORE_SEND=1
export PGG2_LIVE_MAX_RETRIES=0
export PGG2_LIVE_SEND_MODE=rpc
export PGG2_JITO_ENABLED=0
export PGG2_V40_DISABLE_PUMPBC_SAME_ROUTE=1
export PGG2_DIRECT_SELECT_BUYBACK_BY_SIM=0
export PGG2_DIRECT_REQUIRE_SIM_SELECTED_BUYBACK=0
export PGG2_DIRECT_OBSERVED_PAIR_FROM_RAW=1
export PGG2_DIRECT_REQUIRE_OBSERVED_BUYBACK_PAIR=0
export PGG2_V48_LIVE_SKIP_PAIR_PREWARM=1
export PGG2_DIRECT_ACCOUNT_COMMITMENT=processed
export PGG2_DIRECT_BLOCKHASH_COMMITMENT=processed
export PGG2_DIRECT_BLOCKHASH_CACHE_MS="${PGG2_DIRECT_BLOCKHASH_CACHE_MS:-30000}"
export PGG2_V48_LIVE_BLOCKHASH_PREFETCH=1
export PGG2_V48_LIVE_BLOCKHASH_PREFETCH_INTERVAL_MS=1000
export PGG2_V48_LIVE_MINT_OWNER_PREFETCH=1
export PGG2_V48_LIVE_PREFETCH_CONCURRENCY=6
export PGG2_DIRECT_CURVE_ACCOUNT_TTL_SEC=0
export PGG2_DIRECT_PRIORITY_FEE_SOL=0.000020
export PGG2_DIRECT_COMPUTE_UNIT_LIMIT="${PGG2_V51_CU_LIMIT}"
export PGG2_DIRECT_COMPUTE_UNIT_PRICE_MICROLAMPORTS="${PGG2_V51_PRIORITY_FEE_MICROLAMPORTS}"

# Trade sizing -- 0.005 SOL ticket per entry, single open at a time.
export PGG2_LIVE_MAX_TRADE_SOL="${PGG2_LIVE_MAX_TRADE_SOL:-0.005}"
export PGG2_LIVE_MIN_TRADE_SOL="${PGG2_LIVE_MIN_TRADE_SOL:-0.005}"
export PGG2_LIVE_MIN_WALLET_RESERVE_SOL="${PGG2_LIVE_MIN_WALLET_RESERVE_SOL:-0.080}"

# Stop conditions on the V48 layer (mirrors our V51 caps).
export PGG2_V48_TARGET_CLOSED_NONNEG="${PGG2_V51_MAX_CLOSES:-1}"
export PGG2_V48_MAX_OPEN="${PGG2_V51_MAX_OPEN:-1}"
export PGG2_V48_MAX_SECONDS="${PGG2_V51_MAX_SECONDS:-2100}"
export PGG2_V48_CLEAN_CLOSE_ENTRY_FLOOR_SOL="${PGG2_V48_CLEAN_CLOSE_ENTRY_FLOOR_SOL:-0.00120}"
export PGG2_V48_POST_STOP_DRAIN_SECONDS="${PGG2_V48_POST_STOP_DRAIN_SECONDS:-60}"
export PGG2_V48_PROGRESS_INTERVAL_SECONDS="${PGG2_V48_PROGRESS_INTERVAL_SECONDS:-30}"

# V51 exit-stack overrides (TRUE 1500ms hold cap).
export PGG2_V48_LIVE_MAX_POSITION_MS="${PGG2_V51_MAX_HOLD_MS:-1500}"
export PGG2_V48_LIVE_SELL_MIN_PROFIT_SOL="${PGG2_V48_LIVE_SELL_MIN_PROFIT_SOL:--0.0003}"
export PGG2_V48_LIVE_SELL_SEND_MIN_PNL_SOL="${PGG2_V48_LIVE_SELL_SEND_MIN_PNL_SOL:--0.500}"
export PGG2_V48_LIVE_SELL_MIN_OUT_BUFFER_SOL="${PGG2_V48_LIVE_SELL_MIN_OUT_BUFFER_SOL:-0.00005}"
export PGG2_V48_LIVE_EMERGENCY_MIN_SOL_OUT="${PGG2_V48_LIVE_EMERGENCY_MIN_SOL_OUT:-0.0046}"
export PGG2_V48_LIVE_NONBLOCKING_SELL_RETRY=1
export PGG2_V48_LIVE_SELL_MAX_PENDING=2
export PGG2_V48_LIVE_SELL_MAX_SENDS_PER_POSITION=6
export PGG2_V48_LIVE_SELL_PENDING_TIMEOUT_MS=2000
export PGG2_V48_LIVE_SPEC_SELL_WORKER=1
export PGG2_V48_LIVE_SPEC_SELL_MAX_ATTEMPTS=4
export PGG2_V48_LIVE_SPEC_SELL_INTERVAL_MS=100
export PGG2_V48_LIVE_SPEC_SELL_START_DELAY_MS=0
export PGG2_V48_LIVE_SPEC_SELL_REQUIRE_TOKEN_SIGNAL=1
export PGG2_V48_LIVE_USE_ORIGINAL_TOKEN_GUARD=0
export PGG2_V48_LIVE_USE_STRATEGY_TOKEN_GUARD=0
export PGG2_V48_LIVE_FAILED_BUY_MINT_COOLDOWN_MS=60000
export PGG2_V48_LIVE_NOSEND_FAIL_COOLDOWN_MS=1000
export PGG2_V48_LIVE_POSTSIM_EXIT_GATE=1
export PGG2_V48_LIVE_SNAPSHOT_SELL_MAX_AGE_MS=2500
export PGG2_V48_LIVE_MAX_MARKET_GUARD_OVERHANG_PCT=0.12
export PGG2_V48_LIVE_USE_DECISION_CURVE_SNAPSHOT=1
export PGG2_V48_LIVE_USE_SNAPSHOT_SELL=1
export PGG2_V48_LIVE_SNAPSHOT_SELL_CLOSE_ATA=0
export PGG2_V48_LIVE_REVALIDATE_AT_OPEN=1
export PGG2_V48_LIVE_RESYNC_DECISION_TS=1
export PGG2_V48_LIVE_MAX_SNAPSHOT_AGE_AT_SEND_MS=2500
export PGG2_V48_LIVE_MAX_PRESEND_TOKEN_DECAY_PCT=0.20
export PGG2_V48_LIVE_MIN_TOKEN_FRAC=0.55
export PGG2_V48_LIVE_ADAPTIVE_PROFIT_GUARD=1

# V47I safety stack.
export V47I_DRYLIVE=1
export PGG2_V47I_MEDIUM_RUG_VETO=1
export PGG2_V47H_RUG_VETO=1
export PGG2_V47G_SIZE_TIERED_EDGE_FLOOR=1
export PGG2_V47G_LARGE_SIZE_DOWNSIZE=1
export PGG2_V47G_SIZE_HOLD_CAP=1
export PGG2_V47G_MIDHOLD_DUMP_ABORT=1
export PGG2_V48_DRYLIVE_HARNESS=1
export PGG2_V48_CANDIDATE_BACKFILL_QUEUE=1
export PGG2_V48_MAX_SOURCE_LEAD_MS="${PGG2_V48_MAX_SOURCE_LEAD_MS:-3500}"
export PGG2_V48_FEED_STALL_RECONNECT_SECONDS="${PGG2_V48_FEED_STALL_RECONNECT_SECONDS:-45}"

# Freeze rejected paths off.
export PGG2_ENTRY_SNAPSHOT_BANK_ENABLED=0
export PGG2_ENTRY_SNAPSHOT_BANK_LIVE_ELIGIBLE=0
export PGG2_SAME_ROUTE_RECOVERY_ACTUAL_ENTRY_ENABLED=0
export PGG2_PROTECTED_HOLD_ENABLED=0

# ===========================================================================
# OUTPUT PATHS
# ===========================================================================
export PGG2_V48_OUT_MD=/root/piggy/V51_STAGEA_V48_DECISIONS.md
export PGG2_V48_OUT_JSONL=/root/piggy/data/v51_stagea_decisions.jsonl
export PGG2_V48_DEBUG_LOG=/root/piggy/logs/v51_stagea_v48.debug.log
export PGG2_V51_OUT_MD=/root/piggy/V51_STAGEA_HOLDERVETO_RESULT.md

LOG_DIR=/root/piggy/logs
mkdir -p "$LOG_DIR" /root/piggy/data
TS="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="$LOG_DIR/v51_stagea_${TS}.log"

# Safety: ensure no stop file lingers.
rm -f /root/piggy/V51_STOP

echo "[v51-stagea-launch] starting $(date -u +%FT%TZ) -> $LOG_FILE" | tee -a "$LOG_FILE"

PYTHON_BIN="${PYTHON_BIN:-/root/piggy/venv/bin/python}"
if [[ ! -x "$PYTHON_BIN" ]]; then
  PYTHON_BIN="$(command -v python3)"
fi

exec "$PYTHON_BIN" -u /root/piggy/pgg2_v51_stagea_live.py 2>&1 | tee -a "$LOG_FILE"
