#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# Phase 8 2026-05-08 dry-live wrapper.
# Research-derived OFFENSIVE exit architecture:
# - TIERED SCALE-OUT (MemeTrans 41k tokens): 60% at peak 2x + 50% of remaining at 4x
# - STALL EXIT (Marino 184k launches): 75% partial if no new peak in 20s
# - Combined with Phase 7D full-size positions and Phase 7C tightened trail
# - Mathematical advantage: scale-out beats single-shot by +56% loss-mitigation

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_phase8_drylive}"

# Phase 2A — adaptive guards + filter pruning
export PGG2_PRICED_SNAP_BLOCK_TOP700=1.01
export PGG2_LIVE_BLOCK_HHI700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE1500_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_PER_BUYER_ABOVE=99999
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_TIGHT=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_BELOW=0
export PGG2_BLOCK_HOURS_UTC="${PGG2_BLOCK_HOURS_UTC:-18,19,20}"
export PGG2_CIRCUIT_BREAKER_LOSSES="${PGG2_CIRCUIT_BREAKER_LOSSES:-5}"
export PGG2_CIRCUIT_BREAKER_PAUSE_SEC="${PGG2_CIRCUIT_BREAKER_PAUSE_SEC:-300}"

# Phase 3 — keep PEAK-LOCK + curve_lag_reveal
export PGG2_CURVE_LAG_REVEAL_ENABLED="${PGG2_CURVE_LAG_REVEAL_ENABLED:-1}"
export PGG2_PEAK_LOCK_ENABLED="${PGG2_PEAK_LOCK_ENABLED:-1}"
export PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW="${PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW:-1.18}"

# Phase 7D — full-size positions, anti-martingale off
export PGG2_ANTI_MARTINGALE_ENABLED=0
export PGG2_PRICED_SNAP_STANDARD_ENTRY_FRACTION=1.0
export PGG2_PRICED_SNAP_ELITE_ENTRY_FRACTION=1.0
export PGG2_PRICED_SNAP_VERTICAL_ENTRY_FRACTION=1.0
export PGG2_LAYERED_ENTRY_FRACTION=1.0

# Phase 7C — tightened moonshot trail (lock 75-90% of peak)
export PGG2_MOONSHOT_RIDE_ENABLED="${PGG2_MOONSHOT_RIDE_ENABLED:-1}"
export PGG2_MOONSHOT_RIDE_PEAK="${PGG2_MOONSHOT_RIDE_PEAK:-1.15}"
export PGG2_MOONSHOT_RIDE_WINDOW_SEC="${PGG2_MOONSHOT_RIDE_WINDOW_SEC:-90.0}"
export PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC="${PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC:-300.0}"
export PGG2_MOONSHOT_RIDE_TIER0_TRAIL="${PGG2_MOONSHOT_RIDE_TIER0_TRAIL:-0.90}"
export PGG2_MOONSHOT_RIDE_TIER1_PEAK="${PGG2_MOONSHOT_RIDE_TIER1_PEAK:-1.60}"
export PGG2_MOONSHOT_RIDE_TIER1_TRAIL="${PGG2_MOONSHOT_RIDE_TIER1_TRAIL:-0.85}"
export PGG2_MOONSHOT_RIDE_TIER2_PEAK="${PGG2_MOONSHOT_RIDE_TIER2_PEAK:-2.00}"
export PGG2_MOONSHOT_RIDE_TIER2_TRAIL="${PGG2_MOONSHOT_RIDE_TIER2_TRAIL:-0.80}"
export PGG2_MOONSHOT_RIDE_TIER3_PEAK="${PGG2_MOONSHOT_RIDE_TIER3_PEAK:-3.00}"
export PGG2_MOONSHOT_RIDE_TIER3_TRAIL="${PGG2_MOONSHOT_RIDE_TIER3_TRAIL:-0.75}"
export PGG2_MOONSHOT_RIDE_MIN_HOLD_SEC="${PGG2_MOONSHOT_RIDE_MIN_HOLD_SEC:-5.0}"
export PGG2_MOONSHOT_RIDE_PANIC_TRAIL="${PGG2_MOONSHOT_RIDE_PANIC_TRAIL:-0.30}"

# Phase 8 — TIERED SCALE-OUT (research: MemeTrans + Marino papers)
export PGG2_SCALE_OUT_ENABLED="${PGG2_SCALE_OUT_ENABLED:-1}"
export PGG2_SCALE_OUT_TIER1_PEAK="${PGG2_SCALE_OUT_TIER1_PEAK:-2.0}"      # at peak 2x
export PGG2_SCALE_OUT_TIER1_FRACTION="${PGG2_SCALE_OUT_TIER1_FRACTION:-0.60}"  # sell 60% of remaining
export PGG2_SCALE_OUT_TIER2_PEAK="${PGG2_SCALE_OUT_TIER2_PEAK:-4.0}"      # at peak 4x
export PGG2_SCALE_OUT_TIER2_FRACTION="${PGG2_SCALE_OUT_TIER2_FRACTION:-0.50}"  # sell 50% of remaining

# Phase 8 — STALL EXIT (peak hasn't advanced in N seconds + up >15%)
export PGG2_STALL_EXIT_ENABLED="${PGG2_STALL_EXIT_ENABLED:-1}"
export PGG2_STALL_EXIT_SEC="${PGG2_STALL_EXIT_SEC:-20.0}"
export PGG2_STALL_EXIT_MIN_MULT="${PGG2_STALL_EXIT_MIN_MULT:-1.15}"

# Phase 5 — hard_break grace
export PGG2_HARD_BREAK_GRACE_ENABLED="${PGG2_HARD_BREAK_GRACE_ENABLED:-1}"
export PGG2_HARD_BREAK_GRACE_SEC="${PGG2_HARD_BREAK_GRACE_SEC:-8.0}"
export PGG2_HARD_BREAK_GRACE_BUY_AGE_MS="${PGG2_HARD_BREAK_GRACE_BUY_AGE_MS:-1500}"

# Phase 5 — entry window widening
export PGG2_PRICED_SNAP_MAX_AGE_SEC="${PGG2_PRICED_SNAP_MAX_AGE_SEC:-60.0}"
export PGG2_PRICED_SNAP_MAX_MOVE="${PGG2_PRICED_SNAP_MAX_MOVE:-2.50}"
export PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC="${PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC:-60.0}"

# Phase 6/7 — TIERED MIN-HOLD floor
export PGG2_MIN_HOLD_ENABLED="${PGG2_MIN_HOLD_ENABLED:-1}"
export PGG2_MIN_HOLD_SEC="${PGG2_MIN_HOLD_SEC:-12.0}"
export PGG2_MIN_HOLD_LIFE_WINDOW_SEC="${PGG2_MIN_HOLD_LIFE_WINDOW_SEC:-10.0}"
export PGG2_MIN_HOLD_LIFE_PEAK="${PGG2_MIN_HOLD_LIFE_PEAK:-1.10}"
export PGG2_MIN_HOLD_EXTENDED_SEC="${PGG2_MIN_HOLD_EXTENDED_SEC:-90.0}"
export PGG2_MIN_HOLD_PANIC_FLOOR="${PGG2_MIN_HOLD_PANIC_FLOOR:-0.50}"

# Phase 7 — disable moonshot_failed_no_pop
export PIGGY_MOON_FAIL_SEC="${PIGGY_MOON_FAIL_SEC:-999.0}"

exec ./start_pgg2_direct_drylive_candidate.sh
