#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# Phase 7D 2026-05-08 dry-live wrapper.
# WHOLE-BOT STRUCTURAL FIX: position size was 0.015 SOL because layered_risk
# was on AND standard_entry_fraction was 0.30. With 0.015 SOL position and
# 0.002 SOL ATA rent, breakeven hurdle is ~16.5%. That's why 3.83x peak
# trades turned into -$0.14 losses.
#
# Phase 7D: force ALL entries to full 0.05 SOL size. Breakeven drops to ~6.9%.
# Same trades, 3.3x bigger $ outcomes. Anti-martingale off — it was scaling
# down to 0.015 after losses, perpetuating the cost-model death spiral.

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_phase7d_drylive}"

# Phase 2A — adaptive guards + filter pruning
export PGG2_PRICED_SNAP_BLOCK_TOP700=1.01
export PGG2_LIVE_BLOCK_HHI700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE1500_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_PER_BUYER_ABOVE=99999
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_TIGHT=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_BELOW=0
export PGG2_BLOCK_HOURS_UTC="${PGG2_BLOCK_HOURS_UTC:-18,19,20}"
export PGG2_CIRCUIT_BREAKER_LOSSES="${PGG2_CIRCUIT_BREAKER_LOSSES:-5}"
export PGG2_CIRCUIT_BREAKER_PAUSE_SEC="${PGG2_CIRCUIT_BREAKER_PAUSE_SEC:-300}"

# Phase 3 — keep PEAK-LOCK + curve_lag_reveal
export PGG2_CURVE_LAG_REVEAL_ENABLED="${PGG2_CURVE_LAG_REVEAL_ENABLED:-1}"
export PGG2_PEAK_LOCK_ENABLED="${PGG2_PEAK_LOCK_ENABLED:-1}"
export PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW="${PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW:-1.18}"

# Phase 7D — DISABLE anti-martingale (was forcing positions to 0.015 after losses)
export PGG2_ANTI_MARTINGALE_ENABLED=0

# Phase 7D — FORCE FULL-SIZE entries (was 0.015 standard entries)
export PGG2_PRICED_SNAP_STANDARD_ENTRY_FRACTION=1.0
export PGG2_PRICED_SNAP_ELITE_ENTRY_FRACTION=1.0
export PGG2_PRICED_SNAP_VERTICAL_ENTRY_FRACTION=1.0
export PGG2_LAYERED_ENTRY_FRACTION=1.0

# Phase 7C — tightened moonshot trail (lock 75-90% of peak)
export PGG2_MOONSHOT_RIDE_ENABLED="${PGG2_MOONSHOT_RIDE_ENABLED:-1}"
export PGG2_MOONSHOT_RIDE_PEAK="${PGG2_MOONSHOT_RIDE_PEAK:-1.15}"
export PGG2_MOONSHOT_RIDE_WINDOW_SEC="${PGG2_MOONSHOT_RIDE_WINDOW_SEC:-90.0}"
export PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC="${PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC:-300.0}"
export PGG2_MOONSHOT_RIDE_TIER0_TRAIL="${PGG2_MOONSHOT_RIDE_TIER0_TRAIL:-0.90}"
export PGG2_MOONSHOT_RIDE_TIER1_PEAK="${PGG2_MOONSHOT_RIDE_TIER1_PEAK:-1.60}"
export PGG2_MOONSHOT_RIDE_TIER1_TRAIL="${PGG2_MOONSHOT_RIDE_TIER1_TRAIL:-0.85}"
export PGG2_MOONSHOT_RIDE_TIER2_PEAK="${PGG2_MOONSHOT_RIDE_TIER2_PEAK:-2.00}"
export PGG2_MOONSHOT_RIDE_TIER2_TRAIL="${PGG2_MOONSHOT_RIDE_TIER2_TRAIL:-0.80}"
export PGG2_MOONSHOT_RIDE_TIER3_PEAK="${PGG2_MOONSHOT_RIDE_TIER3_PEAK:-3.00}"
export PGG2_MOONSHOT_RIDE_TIER3_TRAIL="${PGG2_MOONSHOT_RIDE_TIER3_TRAIL:-0.75}"
export PGG2_MOONSHOT_RIDE_MIN_HOLD_SEC="${PGG2_MOONSHOT_RIDE_MIN_HOLD_SEC:-5.0}"
export PGG2_MOONSHOT_RIDE_PANIC_TRAIL="${PGG2_MOONSHOT_RIDE_PANIC_TRAIL:-0.30}"

# Phase 5 — hard_break grace
export PGG2_HARD_BREAK_GRACE_ENABLED="${PGG2_HARD_BREAK_GRACE_ENABLED:-1}"
export PGG2_HARD_BREAK_GRACE_SEC="${PGG2_HARD_BREAK_GRACE_SEC:-8.0}"
export PGG2_HARD_BREAK_GRACE_BUY_AGE_MS="${PGG2_HARD_BREAK_GRACE_BUY_AGE_MS:-1500}"

# Phase 5 — entry window widening
export PGG2_PRICED_SNAP_MAX_AGE_SEC="${PGG2_PRICED_SNAP_MAX_AGE_SEC:-60.0}"
export PGG2_PRICED_SNAP_MAX_MOVE="${PGG2_PRICED_SNAP_MAX_MOVE:-2.50}"
export PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC="${PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC:-60.0}"

# Phase 6/7 — TIERED MIN-HOLD floor
export PGG2_MIN_HOLD_ENABLED="${PGG2_MIN_HOLD_ENABLED:-1}"
export PGG2_MIN_HOLD_SEC="${PGG2_MIN_HOLD_SEC:-12.0}"
export PGG2_MIN_HOLD_LIFE_WINDOW_SEC="${PGG2_MIN_HOLD_LIFE_WINDOW_SEC:-10.0}"
export PGG2_MIN_HOLD_LIFE_PEAK="${PGG2_MIN_HOLD_LIFE_PEAK:-1.10}"
export PGG2_MIN_HOLD_EXTENDED_SEC="${PGG2_MIN_HOLD_EXTENDED_SEC:-90.0}"
export PGG2_MIN_HOLD_PANIC_FLOOR="${PGG2_MIN_HOLD_PANIC_FLOOR:-0.50}"

# Phase 7 — disable moonshot_failed_no_pop
export PIGGY_MOON_FAIL_SEC="${PIGGY_MOON_FAIL_SEC:-999.0}"

exec ./start_pgg2_direct_drylive_candidate.sh
