#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# v39 bounded corrected dry-live. Real live stays OFF: execution_mode=quote,
# direct pump builder, send=0. This run captures online lead snapshots and
# permits only v39 live-sequential dry-live entries.

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_v39_online_drylive}"

export PGG2_EXECUTION_MODE=quote
export PGG2_ENABLE_LIVE=1
export PIGGY_PAPER_TRADING=0
export PGG2_DRY_LIVE_MODE=1
export PGG2_LIVE_BROKER=direct_pump
export PGG2_WALLET_KEYPAIR="${PGG2_WALLET_KEYPAIR:-/root/piggy/live_wallet.key}"

export PGG2_QUOTE_SHADOW_POSITIONS=1
export PGG2_QUOTE_SIMULATE=0
export PGG2_LIVE_SIMULATE_BEFORE_SEND=0
export PGG2_LIVE_SKIP_PREFLIGHT=1
export PGG2_LIVE_PREFLIGHT_ROUNDTRIP_ENABLED=0
export PGG2_LIVE_FINAL_ENTRY_GUARD_ENABLED=0
export PGG2_DIRECT_SELECT_BUYBACK_BY_SIM=0
export PGG2_DIRECT_REQUIRE_SIM_SELECTED_BUYBACK=0
export PGG2_DIRECT_OBSERVED_PAIR_FROM_RAW=1
export PGG2_DIRECT_REQUIRE_OBSERVED_BUYBACK_PAIR=1
export PGG2_DIRECT_ACCOUNT_COMMITMENT=processed
export PGG2_DIRECT_BLOCKHASH_COMMITMENT=processed
export PGG2_DIRECT_CURVE_ACCOUNT_TTL_SEC=0
export PGG2_DIRECT_EXIT_ANY_EXECUTABLE_PRICE=1
export PGG2_DIRECT_EXIT_MIN_LAMPORTS=1

# v39 online lead capture and actual dry-live entries.
export PGG2_V39_LEAD_TIME_SCALP_ENABLED=1
export PGG2_V39_ONLINE_LEAD_CAPTURE_ENABLED=1
export PGG2_V39_DRYLIVE_ACTUAL_ENTRY_ENABLED=1
export PGG2_ACTUAL_ENTRY_MASTER_ENABLED=1
export PGG2_V39_TARGET_ENTRIES=10
export PGG2_V39_MAX_OPEN=5
export PIGGY_MAX_OPEN=5
export PIGGY_MAX_OPEN_POSITIONS=5
export PGG2_V39_LEAD_SNAPSHOT_MS="${PGG2_V39_LEAD_SNAPSHOT_MS:-0,100,250,500,750,1000,1500,2000,3000}"
export PGG2_V39_ENTRY_MIN_PROCESSED_PNL_SOL="${PGG2_V39_ENTRY_MIN_PROCESSED_PNL_SOL:-0.00020}"
export PGG2_V39_BANK_PNL_SOL="${PGG2_V39_BANK_PNL_SOL:-0.00060}"
export PGG2_V39_SCRATCH_PNL_SOL="${PGG2_V39_SCRATCH_PNL_SOL:-0.00005}"
export PGG2_V39_CLAMP_LOSS_SOL="${PGG2_V39_CLAMP_LOSS_SOL:-0.00050}"
export PGG2_V39_MAX_HOLD_MS="${PGG2_V39_MAX_HOLD_MS:-3000}"
export PGG2_V39_ABSOLUTE_MAX_HOLD_MS="${PGG2_V39_ABSOLUTE_MAX_HOLD_MS:-5000}"
export PGG2_V39_MAX_SELL_LATENCY_MS="${PGG2_V39_MAX_SELL_LATENCY_MS:-750}"

# Disable old entry families/substitutes for this run.
export PGG2_DRYLIVE_PILOT_ENABLED=0
export PGG2_SCALP_ENABLED=0
export PGG2_SHADOW_LAB_CANARY_ACTUAL_ENTRY=0
export PGG2_ENTRY_SNAPSHOT_BANK_ENABLED=0
export PGG2_ENTRY_SNAPSHOT_BANK_LIVE_ELIGIBLE=0

# Keep the sampler wide enough to capture the missing lead evidence while
# leaving entry permission to the v39 live-sequential gates.
export PGG2_SHADOW_LAB_ENABLED=1
export PGG2_SHADOW_OBSERVE_ENABLED=1
export PGG2_SHADOW_LAB_MAX_CONCURRENT="${PGG2_SHADOW_LAB_MAX_CONCURRENT:-8}"
export PGG2_SHADOW_LAB_COOLDOWN_MS="${PGG2_SHADOW_LAB_COOLDOWN_MS:-12000}"
export PGG2_SHADOW_OBSERVE_MIN_SOL_V39_LEAD="${PGG2_SHADOW_OBSERVE_MIN_SOL_V39_LEAD:-0.0}"
export PGG2_V39_LEAD_MIN_BUY_SOL_700="${PGG2_V39_LEAD_MIN_BUY_SOL_700:-0.70}"
export PGG2_V39_LEAD_MIN_BUYERS_700="${PGG2_V39_LEAD_MIN_BUYERS_700:-1}"
export PGG2_V39_LEAD_MAX_TOP_SHARE_700="${PGG2_V39_LEAD_MAX_TOP_SHARE_700:-1.0}"
export PGG2_V39_LEAD_MAX_SELL_RATIO_700="${PGG2_V39_LEAD_MAX_SELL_RATIO_700:-0.35}"

export PGG2_RISK_WORKER_ENABLED=1
export PGG2_RISK_WORKER_OWNS_QUOTE_EXIT=1
export PGG2_RISK_ALLOW_OVERLAP_QUOTES=0
export PGG2_QUOTE_MGR_CACHE_TTL_MS=300
export PGG2_QUOTE_MGR_REFRESH_AFTER_MS=200

export PGG2_LIVE_BUY_SLIPPAGE_PCT="${PGG2_LIVE_BUY_SLIPPAGE_PCT:-65}"
export PGG2_LIVE_SELL_SLIPPAGE_PCT="${PGG2_LIVE_SELL_SLIPPAGE_PCT:-99}"
export PGG2_LIVE_MAX_TRADE_SOL=0.015
export PGG2_LIVE_MIN_TRADE_SOL=0.015
export PGG2_LIVE_MIN_WALLET_RESERVE_SOL="${PGG2_LIVE_MIN_WALLET_RESERVE_SOL:-0.080}"
export PGG2_LIVE_MAX_SESSION_LOSS_SOL=999
export PGG2_LIVE_MAX_CONSECUTIVE_LOSSES=999

exec ./start_pgg2_direct_drylive_candidate.sh
