#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

if [[ "${PGG2_V48_LIVE_SMOKE_ENABLED:-0}" == "1" ]]; then
  export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_v48_live_smoke}"

  # V48 live smoke uses this same harness and the same V48 gates. Only the
  # execution adapter changes from dry-live accounting to direct Pump live.
  export PGG2_EXECUTION_MODE=live
  export PGG2_ENABLE_LIVE=1
  export PIGGY_PAPER_TRADING=0
  export PGG2_DRY_LIVE_MODE=0
  export PGG2_LIVE_BROKER=direct_pump
  export PGG2_WALLET_KEYPAIR="${PGG2_WALLET_KEYPAIR:-/root/piggy/live_wallet.key}"
  export PGG2_LIVE_CONFIRM="${PGG2_LIVE_CONFIRM:-I_ACCEPT_REAL_SOL_RISK}"
  export PGG2_DIRECT_LIVE_CONFIRM="${PGG2_DIRECT_LIVE_CONFIRM:-I_ACCEPT_DIRECT_PUMP_RISK}"
  export PGG2_QUOTE_SHADOW_POSITIONS=0
  export PGG2_QUOTE_SIMULATE=0
  export PGG2_LIVE_SIMULATE_BEFORE_SEND=0
  export PGG2_LIVE_SKIP_PREFLIGHT="${PGG2_LIVE_SKIP_PREFLIGHT:-1}"
  export PGG2_LIVE_SEND_MODE=rpc
  export PGG2_JITO_ENABLED=0
  export PGG2_DIRECT_SELECT_BUYBACK_BY_SIM=0
  export PGG2_DIRECT_REQUIRE_SIM_SELECTED_BUYBACK=0
  export PGG2_DIRECT_OBSERVED_PAIR_FROM_RAW=1
  # V48 dry-live does not have an observed-pair requirement. For this live
  # smoke, missing current-sig/confirmed pair data must not become an extra
  # strategy gate; the direct builder may use its default non-sim Pump pair.
  export PGG2_DIRECT_REQUIRE_OBSERVED_BUYBACK_PAIR=0
  export PGG2_V48_LIVE_SKIP_PAIR_PREWARM="${PGG2_V48_LIVE_SKIP_PAIR_PREWARM:-1}"
  export PGG2_DIRECT_ACCOUNT_COMMITMENT=processed
  export PGG2_DIRECT_BLOCKHASH_COMMITMENT=processed
  export PGG2_DIRECT_BLOCKHASH_CACHE_MS="${PGG2_DIRECT_BLOCKHASH_CACHE_MS:-30000}"
  export PGG2_V48_LIVE_BLOCKHASH_PREFETCH="${PGG2_V48_LIVE_BLOCKHASH_PREFETCH:-1}"
  export PGG2_V48_LIVE_BLOCKHASH_PREFETCH_INTERVAL_MS="${PGG2_V48_LIVE_BLOCKHASH_PREFETCH_INTERVAL_MS:-1000}"
  export PGG2_V48_LIVE_MINT_OWNER_PREFETCH="${PGG2_V48_LIVE_MINT_OWNER_PREFETCH:-1}"
  export PGG2_V48_LIVE_PREFETCH_CONCURRENCY="${PGG2_V48_LIVE_PREFETCH_CONCURRENCY:-6}"
  export PGG2_DIRECT_CURVE_ACCOUNT_TTL_SEC=0
  export PGG2_DIRECT_PRIORITY_FEE_SOL="${PGG2_DIRECT_PRIORITY_FEE_SOL:-0.000075}"
  export PGG2_LIVE_MAX_TRADE_SOL="${PGG2_LIVE_MAX_TRADE_SOL:-0.005}"
  export PGG2_LIVE_MIN_TRADE_SOL="${PGG2_LIVE_MIN_TRADE_SOL:-0.005}"
  export PGG2_LIVE_MIN_WALLET_RESERVE_SOL="${PGG2_LIVE_MIN_WALLET_RESERVE_SOL:-0.080}"
  export PGG2_LIVE_MAX_SESSION_LOSS_SOL="${PGG2_LIVE_MAX_SESSION_LOSS_SOL:-999}"
  export PGG2_LIVE_MAX_CONSECUTIVE_LOSSES="${PGG2_LIVE_MAX_CONSECUTIVE_LOSSES:-999}"
  export PGG2_V48_TARGET_CLOSED_NONNEG="${PGG2_V48_TARGET_CLOSED_NONNEG:-1}"
  export PGG2_V48_MAX_OPEN="${PGG2_V48_MAX_OPEN:-1}"
  export PGG2_V48_MAX_SECONDS="${PGG2_V48_MAX_SECONDS:-120}"
  export PGG2_V48_CLEAN_CLOSE_ENTRY_FLOOR_SOL="${PGG2_V48_CLEAN_CLOSE_ENTRY_FLOOR_SOL:-0.00120}"
  export PGG2_V48_POST_STOP_DRAIN_SECONDS="${PGG2_V48_POST_STOP_DRAIN_SECONDS:-20}"
  export PGG2_V48_PROGRESS_INTERVAL_SECONDS="${PGG2_V48_PROGRESS_INTERVAL_SECONDS:-15}"
  export PGG2_V48_LIVE_MAX_POSITION_MS="${PGG2_V48_LIVE_MAX_POSITION_MS:-30000}"
  export PGG2_V48_LIVE_SELL_MIN_PROFIT_SOL="${PGG2_V48_LIVE_SELL_MIN_PROFIT_SOL:-0.00000}"
  export PGG2_V48_LIVE_SELL_SEND_MIN_PNL_SOL="${PGG2_V48_LIVE_SELL_SEND_MIN_PNL_SOL:-0.00025}"
  export PGG2_V48_LIVE_SELL_MIN_OUT_BUFFER_SOL="${PGG2_V48_LIVE_SELL_MIN_OUT_BUFFER_SOL:-0.00005}"
  export PGG2_V48_LIVE_NONBLOCKING_SELL_RETRY="${PGG2_V48_LIVE_NONBLOCKING_SELL_RETRY:-1}"
  export PGG2_V48_LIVE_SELL_MAX_PENDING="${PGG2_V48_LIVE_SELL_MAX_PENDING:-2}"
  export PGG2_V48_LIVE_SELL_MAX_SENDS_PER_POSITION="${PGG2_V48_LIVE_SELL_MAX_SENDS_PER_POSITION:-4}"
  export PGG2_V48_LIVE_SELL_PENDING_TIMEOUT_MS="${PGG2_V48_LIVE_SELL_PENDING_TIMEOUT_MS:-3500}"
  export PGG2_V48_LIVE_SPEC_SELL_WORKER="${PGG2_V48_LIVE_SPEC_SELL_WORKER:-1}"
  export PGG2_V48_LIVE_SPEC_SELL_MAX_ATTEMPTS="${PGG2_V48_LIVE_SPEC_SELL_MAX_ATTEMPTS:-8}"
  export PGG2_V48_LIVE_SPEC_SELL_INTERVAL_MS="${PGG2_V48_LIVE_SPEC_SELL_INTERVAL_MS:-100}"
  export PGG2_V48_LIVE_SPEC_SELL_START_DELAY_MS="${PGG2_V48_LIVE_SPEC_SELL_START_DELAY_MS:-0}"
  export PGG2_V48_LIVE_SPEC_SELL_REQUIRE_TOKEN_SIGNAL="${PGG2_V48_LIVE_SPEC_SELL_REQUIRE_TOKEN_SIGNAL:-1}"
  export PGG2_V48_LIVE_ADAPTIVE_PROFIT_GUARD="${PGG2_V48_LIVE_ADAPTIVE_PROFIT_GUARD:-1}"
  export PGG2_V48_LIVE_REQUIRE_IMMEDIATE_BREAKEVEN_MIN_TOKEN="${PGG2_V48_LIVE_REQUIRE_IMMEDIATE_BREAKEVEN_MIN_TOKEN:-0}"
  export PGG2_V48_LIVE_USE_ORIGINAL_TOKEN_GUARD="${PGG2_V48_LIVE_USE_ORIGINAL_TOKEN_GUARD:-0}"
  export PGG2_V48_LIVE_USE_STRATEGY_TOKEN_GUARD="${PGG2_V48_LIVE_USE_STRATEGY_TOKEN_GUARD:-0}"
  export PGG2_V48_LIVE_FAILED_BUY_MINT_COOLDOWN_MS="${PGG2_V48_LIVE_FAILED_BUY_MINT_COOLDOWN_MS:-60000}"
  export PGG2_V48_LIVE_NOSEND_FAIL_COOLDOWN_MS="${PGG2_V48_LIVE_NOSEND_FAIL_COOLDOWN_MS:-1000}"
  export PGG2_V48_LIVE_SIMULATE_BUY_BEFORE_SEND="${PGG2_V48_LIVE_SIMULATE_BUY_BEFORE_SEND:-1}"
  export PGG2_V48_LIVE_POSTSIM_EXIT_GATE="${PGG2_V48_LIVE_POSTSIM_EXIT_GATE:-1}"
  export PGG2_V48_LIVE_SNAPSHOT_SELL_MAX_AGE_MS="${PGG2_V48_LIVE_SNAPSHOT_SELL_MAX_AGE_MS:-750}"
  export PGG2_V48_LIVE_MAX_MARKET_GUARD_OVERHANG_PCT="${PGG2_V48_LIVE_MAX_MARKET_GUARD_OVERHANG_PCT:-0.12}"
  export PGG2_V48_LIVE_MAX_PRESEND_TOKEN_DECAY_PCT="${PGG2_V48_LIVE_MAX_PRESEND_TOKEN_DECAY_PCT:-0.20}"
  export PGG2_V48_LIVE_MIN_TOKEN_FRAC="${PGG2_V48_LIVE_MIN_TOKEN_FRAC:-0.55}"
  export PGG2_V48_LIVE_USE_DECISION_CURVE_SNAPSHOT="${PGG2_V48_LIVE_USE_DECISION_CURVE_SNAPSHOT:-1}"
  export PGG2_V48_LIVE_USE_SNAPSHOT_SELL="${PGG2_V48_LIVE_USE_SNAPSHOT_SELL:-1}"
  export PGG2_V48_LIVE_SNAPSHOT_SELL_CLOSE_ATA="${PGG2_V48_LIVE_SNAPSHOT_SELL_CLOSE_ATA:-0}"
  export PGG2_V48_LIVE_REVALIDATE_AT_OPEN="${PGG2_V48_LIVE_REVALIDATE_AT_OPEN:-1}"
  export PGG2_V48_LIVE_RESYNC_DECISION_TS="${PGG2_V48_LIVE_RESYNC_DECISION_TS:-1}"
  export PGG2_V48_LIVE_MAX_SNAPSHOT_AGE_AT_SEND_MS="${PGG2_V48_LIVE_MAX_SNAPSHOT_AGE_AT_SEND_MS:-750}"
  export PGG2_V48_OUT_MD="${PGG2_V48_OUT_MD:-V48_LIVE_SMOKE_RESULT.md}"
  export PGG2_V48_OUT_JSONL="${PGG2_V48_OUT_JSONL:-data/v48_live_smoke_decisions.jsonl}"
else
  export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_v48_drylive_harness}"

  # V48 default is dry-live only. No real transactions, no paid feeds, no Jito.
  export PGG2_EXECUTION_MODE=quote
  export PGG2_ENABLE_LIVE=0
  export PIGGY_PAPER_TRADING=0
  export PGG2_DRY_LIVE_MODE=1
fi
export PGG2_V40_DISABLE_PUMPBC_SAME_ROUTE=1
export PGG2_V48_DRYLIVE_HARNESS=1
export PGG2_V48_CANDIDATE_BACKFILL_QUEUE=1
export PGG2_V48_MAX_SOURCE_LEAD_MS="${PGG2_V48_MAX_SOURCE_LEAD_MS:-1500}"
export PGG2_V48_FEED_STALL_RECONNECT_SECONDS="${PGG2_V48_FEED_STALL_RECONNECT_SECONDS:-45}"

# Freeze the V47B/C/D/E/F/G/H/I safe stack.
export V47I_DRYLIVE=1
export PGG2_V47I_MEDIUM_RUG_VETO=1
export PGG2_V47H_RUG_VETO=1
export PGG2_V47G_SIZE_TIERED_EDGE_FLOOR=1
export PGG2_V47G_LARGE_SIZE_DOWNSIZE=1
export PGG2_V47G_SIZE_HOLD_CAP=1
export PGG2_V47G_MIDHOLD_DUMP_ABORT=1

# Explicitly keep rejected production paths off.
export PGG2_ENTRY_SNAPSHOT_BANK_ENABLED=0
export PGG2_ENTRY_SNAPSHOT_BANK_LIVE_ELIGIBLE=0
export PGG2_SAME_ROUTE_RECOVERY_ACTUAL_ENTRY_ENABLED=0
export PGG2_PROTECTED_HOLD_ENABLED=0
export PGG2_JITO_ENABLED=0
export PGG2_LIVE_SEND_MODE=rpc

if [[ "${PGG2_V48_LIVE_SMOKE_ENABLED:-0}" == "1" ]]; then
  RUNID="${RUNID:-pgg2_v48_live_smoke_$(date +%Y%m%d_%H%M%S)}"
else
  RUNID="${RUNID:-pgg2_v48_drylive_harness_$(date +%Y%m%d_%H%M%S)}"
fi
mkdir -p logs data
echo "$RUNID" > current_pgg2_v48_drylive_runid.txt
if [[ "${PGG2_V48_LIVE_SMOKE_ENABLED:-0}" == "1" ]]; then
  echo "$RUNID" > current_pgg2_v48_live_smoke_runid.txt
fi

PYTHON_BIN="${PYTHON_BIN:-/root/piggy/venv/bin/python}"
if [[ ! -x "$PYTHON_BIN" ]]; then
  PYTHON_BIN="$(command -v python3)"
fi

exec "$PYTHON_BIN" -u pgg2_v48_drylive_harness.py \
  --out-md "${PGG2_V48_OUT_MD:-V48_CORRECTED_DRYLIVE_RESULT.md}" \
  --out-jsonl "${PGG2_V48_OUT_JSONL:-data/v48_drylive_decisions.jsonl}" \
  --debug-log "logs/${RUNID}.debug.log" \
  --max-seconds "${PGG2_V48_MAX_SECONDS:-2100}" \
  --target-non-neg-closes "${PGG2_V48_TARGET_CLOSED_NONNEG:-10}" \
  --max-open-positions "${PGG2_V48_MAX_OPEN:-2}" \
  --backfill-ttl-ms "${PGG2_V48_BACKFILL_TTL_MS:-1000}" \
  --clean-close-entry-floor-sol "${PGG2_V48_CLEAN_CLOSE_ENTRY_FLOOR_SOL:-0.00120}" \
  --profit-reentry-block-ms "${PGG2_V48_PROFIT_REENTRY_BLOCK_MS:-30000}" \
  --concentration-guard-max-buyers "${PGG2_V48_CONCENTRATION_GUARD_MAX_BUYERS:-4}" \
  --concentration-guard-top-share "${PGG2_V48_CONCENTRATION_GUARD_TOP_SHARE:-0.55}" \
  --velocity-edge-max-buyers "${PGG2_V48_VELOCITY_EDGE_MAX_BUYERS:-4}" \
  --velocity-edge-min-buy-sol "${PGG2_V48_VELOCITY_EDGE_MIN_BUY_SOL:-6.0}" \
  --velocity-edge-floor-sol "${PGG2_V48_VELOCITY_EDGE_FLOOR_SOL:-0.00140}" \
  --recent-v47i-veto-memory-ms "${PGG2_V48_RECENT_V47I_VETO_MEMORY_MS:-2000}" \
  --post-stop-drain-seconds "${PGG2_V48_POST_STOP_DRAIN_SECONDS:-300}" \
  --failed-buy-fee-budget-sol "${PGG2_V48_FAILED_BUY_FEE_BUDGET_SOL:-0.00300}" \
  --progress-interval-seconds "${PGG2_V48_PROGRESS_INTERVAL_SECONDS:-60}"
