#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# Phase 7 2026-05-08 dry-live wrapper.
# Phase 6 autopsy: 2iStU7GGt8b1sY peaked 1.16x at 5.7s, exited at 17s,
# mint's TRUE peak was 7.97x at 276s post-entry. Min-hold of 12s was
# 4 minutes too short. moonshot_failed_no_pop fired at 18s killing the trade
# before pump developed.
#
# Phase 7 fixes:
# (1) Lower moonshot latch from 1.30 → 1.15. LOSS #2 peaked 1.16, would now latch.
# (2) TIERED hold: if peak >= 1.10 in first 10s, extend to 90s. Else 12s.
# (3) Widen moonshot arm_window 30s → 90s to match extended hold.
# (4) Disable moonshot_failed_no_pop (PIGGY_MOON_FAIL_SEC=999).

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_phase7_drylive}"

# Phase 2A — adaptive guards + filter pruning
export PGG2_PRICED_SNAP_BLOCK_TOP700=1.01
export PGG2_LIVE_BLOCK_HHI700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE1500_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_PER_BUYER_ABOVE=99999
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_TIGHT=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_BELOW=0
export PGG2_BLOCK_HOURS_UTC="${PGG2_BLOCK_HOURS_UTC:-18,19,20}"
export PGG2_CIRCUIT_BREAKER_LOSSES="${PGG2_CIRCUIT_BREAKER_LOSSES:-5}"
export PGG2_CIRCUIT_BREAKER_PAUSE_SEC="${PGG2_CIRCUIT_BREAKER_PAUSE_SEC:-300}"

# Phase 3 — keep PEAK-LOCK + curve_lag_reveal
export PGG2_CURVE_LAG_REVEAL_ENABLED="${PGG2_CURVE_LAG_REVEAL_ENABLED:-1}"
export PGG2_PEAK_LOCK_ENABLED="${PGG2_PEAK_LOCK_ENABLED:-1}"
export PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW="${PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW:-1.18}"
export PGG2_ANTI_MARTINGALE_ENABLED="${PGG2_ANTI_MARTINGALE_ENABLED:-1}"
export PGG2_ANTI_MARTINGALE_LOSS_STREAK="${PGG2_ANTI_MARTINGALE_LOSS_STREAK:-2}"
export PGG2_ANTI_MARTINGALE_LOSS_SCALE="${PGG2_ANTI_MARTINGALE_LOSS_SCALE:-0.50}"
export PGG2_ANTI_MARTINGALE_WIN_STREAK="${PGG2_ANTI_MARTINGALE_WIN_STREAK:-2}"
export PGG2_ANTI_MARTINGALE_WIN_SCALE="${PGG2_ANTI_MARTINGALE_WIN_SCALE:-1.30}"

# Phase 7 — MOONSHOT-RIDER with lower latch + wider window
export PGG2_MOONSHOT_RIDE_ENABLED="${PGG2_MOONSHOT_RIDE_ENABLED:-1}"
export PGG2_MOONSHOT_RIDE_PEAK="${PGG2_MOONSHOT_RIDE_PEAK:-1.15}"          # was 1.30
export PGG2_MOONSHOT_RIDE_WINDOW_SEC="${PGG2_MOONSHOT_RIDE_WINDOW_SEC:-90.0}"  # was 30
export PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC="${PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC:-300.0}"  # 5 min cap
export PGG2_MOONSHOT_RIDE_TIER0_TRAIL="${PGG2_MOONSHOT_RIDE_TIER0_TRAIL:-0.85}"  # peak < 1.60
export PGG2_MOONSHOT_RIDE_TIER1_PEAK="${PGG2_MOONSHOT_RIDE_TIER1_PEAK:-1.60}"
export PGG2_MOONSHOT_RIDE_TIER1_TRAIL="${PGG2_MOONSHOT_RIDE_TIER1_TRAIL:-0.80}"
export PGG2_MOONSHOT_RIDE_TIER2_PEAK="${PGG2_MOONSHOT_RIDE_TIER2_PEAK:-2.00}"
export PGG2_MOONSHOT_RIDE_TIER2_TRAIL="${PGG2_MOONSHOT_RIDE_TIER2_TRAIL:-0.60}"
export PGG2_MOONSHOT_RIDE_TIER3_PEAK="${PGG2_MOONSHOT_RIDE_TIER3_PEAK:-3.00}"
export PGG2_MOONSHOT_RIDE_TIER3_TRAIL="${PGG2_MOONSHOT_RIDE_TIER3_TRAIL:-0.40}"
export PGG2_MOONSHOT_RIDE_MIN_HOLD_SEC="${PGG2_MOONSHOT_RIDE_MIN_HOLD_SEC:-5.0}"
export PGG2_MOONSHOT_RIDE_PANIC_TRAIL="${PGG2_MOONSHOT_RIDE_PANIC_TRAIL:-0.30}"

# Phase 5 — hard_break grace
export PGG2_HARD_BREAK_GRACE_ENABLED="${PGG2_HARD_BREAK_GRACE_ENABLED:-1}"
export PGG2_HARD_BREAK_GRACE_SEC="${PGG2_HARD_BREAK_GRACE_SEC:-8.0}"
export PGG2_HARD_BREAK_GRACE_BUY_AGE_MS="${PGG2_HARD_BREAK_GRACE_BUY_AGE_MS:-1500}"

# Phase 5 — entry window widening (priced_snap)
export PGG2_PRICED_SNAP_MAX_AGE_SEC="${PGG2_PRICED_SNAP_MAX_AGE_SEC:-60.0}"
export PGG2_PRICED_SNAP_MAX_MOVE="${PGG2_PRICED_SNAP_MAX_MOVE:-2.50}"
export PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC="${PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC:-60.0}"

# Phase 6/7 — TIERED MIN-HOLD floor for priced_snap + curve_lag_reveal
export PGG2_MIN_HOLD_ENABLED="${PGG2_MIN_HOLD_ENABLED:-1}"
export PGG2_MIN_HOLD_SEC="${PGG2_MIN_HOLD_SEC:-12.0}"
export PGG2_MIN_HOLD_LIFE_WINDOW_SEC="${PGG2_MIN_HOLD_LIFE_WINDOW_SEC:-10.0}"
export PGG2_MIN_HOLD_LIFE_PEAK="${PGG2_MIN_HOLD_LIFE_PEAK:-1.10}"
export PGG2_MIN_HOLD_EXTENDED_SEC="${PGG2_MIN_HOLD_EXTENDED_SEC:-90.0}"
export PGG2_MIN_HOLD_PANIC_FLOOR="${PGG2_MIN_HOLD_PANIC_FLOOR:-0.50}"

# Phase 7 — disable moonshot_failed_no_pop (was firing at 18s on peak<1.18)
export PIGGY_MOON_FAIL_SEC="${PIGGY_MOON_FAIL_SEC:-999.0}"

exec ./start_pgg2_direct_drylive_candidate.sh
