#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# Experimentalji runs the production candidate's live-equivalent dry-live
# profile, but swaps the entry file to experimentalji.py and enables the
# multi-source router. It never sends real SOL in this mode.
export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-experimentalji_direct_drylive}"
export PGG2_EXECUTION_MODE=quote
export PGG2_ENABLE_LIVE=1
export PIGGY_PAPER_TRADING=0
export PGG2_DRY_LIVE_MODE=1
export PGG2_LIVE_BROKER=direct_pump
export PGG2_WALLET_KEYPAIR="${PGG2_WALLET_KEYPAIR:-/root/piggy/live_wallet.key}"

# Load the current direct-cost candidate profile without its final exec. This
# keeps experimentalji on the same live-equivalent profile as the active PGG2
# dry-live run, including the toxic/loss-cutter settings layered on top of the
# attack profile.
source <(sed '/^exec \.\/start_pgg2_attack_paper.sh/,$d' ./start_pgg2_direct_drylive_candidate.sh)

# Load the underlying attack profile without its final PGG2.py exec. It creates
# the run id and exports the base lane configuration; the candidate profile
# above wins where it provided stricter defaults.
source <(sed '/^exec \.\/venv\/bin\/python -u PGG2.py/,$d' ./start_pgg2_attack_paper.sh)

# Reassert exact direct quote-mode live mirror after the profile load.
export PGG2_EXECUTION_MODE=quote
export PGG2_ENABLE_LIVE=1
export PIGGY_PAPER_TRADING=0
export PGG2_DRY_LIVE_MODE=1
export PGG2_LIVE_BROKER=direct_pump
export PGG2_QUOTE_SHADOW_POSITIONS=1
export PGG2_QUOTE_SIMULATE=0
export PGG2_LIVE_SIMULATE_BEFORE_SEND=0
export PGG2_LIVE_SKIP_PREFLIGHT=1
# No Solana simulation/preflight transaction round trip. This is only a direct
# Pump/PumpSwap buy quote + immediate direct sell quote check, using the same
# execution route the live bot would use. The current dry-live loss tape showed
# this is necessary: several entries were already deeply red on the executable
# sell quote before the bot could manage them.
export PGG2_LIVE_PREFLIGHT_ROUNDTRIP_ENABLED=1
export PGG2_LIVE_FINAL_ENTRY_GUARD_ENABLED=1
export PGG2_LIVE_ENTRY_STABILITY_CONFIRM_ENABLED="${PGG2_LIVE_ENTRY_STABILITY_CONFIRM_ENABLED:-1}"
export PGG2_LIVE_ENTRY_STABILITY_CONFIRM_LANES="${PGG2_LIVE_ENTRY_STABILITY_CONFIRM_LANES:-priced_snap}"
export PGG2_LIVE_ENTRY_STABILITY_DELAY_MS="${PGG2_LIVE_ENTRY_STABILITY_DELAY_MS:-450}"
export PGG2_LIVE_ENTRY_STABILITY_RAW_MOMENTUM_DELAY_MS="${PGG2_LIVE_ENTRY_STABILITY_RAW_MOMENTUM_DELAY_MS:-0}"
export PGG2_LIVE_ENTRY_STABILITY_PRICED_SNAP_DELAY_MS="${PGG2_LIVE_ENTRY_STABILITY_PRICED_SNAP_DELAY_MS:-450}"
export PGG2_LIVE_ENTRY_STABILITY_PRICED_SNAP_MIN_PNL_SOL="${PGG2_LIVE_ENTRY_STABILITY_PRICED_SNAP_MIN_PNL_SOL:-0.00050}"
export PGG2_LIVE_ENTRY_STABILITY_RAW_MOMENTUM_MIN_PNL_SOL="${PGG2_LIVE_ENTRY_STABILITY_RAW_MOMENTUM_MIN_PNL_SOL:-0.00010}"
export PGG2_LIVE_FINAL_ENTRY_COMMIT_CONFIRM_ENABLED="${PGG2_LIVE_FINAL_ENTRY_COMMIT_CONFIRM_ENABLED:-1}"
export PGG2_LIVE_FINAL_ENTRY_COMMIT_CONFIRM_LANES="${PGG2_LIVE_FINAL_ENTRY_COMMIT_CONFIRM_LANES:-raw_momentum,priced_snap,curve_lag_reveal}"
export PGG2_LIVE_FINAL_ENTRY_COMMIT_CONFIRM_DELAY_MS="${PGG2_LIVE_FINAL_ENTRY_COMMIT_CONFIRM_DELAY_MS:-0}"
export PGG2_LIVE_FINAL_ENTRY_COMMIT_RAW_MOMENTUM_MIN_PNL_SOL="${PGG2_LIVE_FINAL_ENTRY_COMMIT_RAW_MOMENTUM_MIN_PNL_SOL:-0.00010}"
export PGG2_LIVE_FINAL_ENTRY_COMMIT_PRICED_SNAP_MIN_PNL_SOL="${PGG2_LIVE_FINAL_ENTRY_COMMIT_PRICED_SNAP_MIN_PNL_SOL:-0.00050}"
export PGG2_LIVE_FINAL_ENTRY_COMMIT_CURVE_LAG_MIN_PNL_SOL="${PGG2_LIVE_FINAL_ENTRY_COMMIT_CURVE_LAG_MIN_PNL_SOL:-0.00075}"
export PGG2_LIVE_FINAL_ENTRY_COMMIT_RAW_TINY_RED_MIN_PNL_SOL="${PGG2_LIVE_FINAL_ENTRY_COMMIT_RAW_TINY_RED_MIN_PNL_SOL:--0.00110}"
export PGG2_LIVE_FINAL_ENTRY_COMMIT_MIN_RETENTION="${PGG2_LIVE_FINAL_ENTRY_COMMIT_MIN_RETENTION:-0.82}"
export PGG2_LIVE_PRICED_SNAP_MAX_ROUNDTRIP_LOSS_RATIO="${PGG2_LIVE_PRICED_SNAP_MAX_ROUNDTRIP_LOSS_RATIO:-0.045}"
export PGG2_LIVE_PRICED_SNAP_ROUNDTRIP_ABS_FLOOR_SOL="${PGG2_LIVE_PRICED_SNAP_ROUNDTRIP_ABS_FLOOR_SOL:-0.00150}"
export PGG2_LIVE_PRICED_SNAP_BROAD_ROUNDTRIP_EXCEPTION_ENABLED="${PGG2_LIVE_PRICED_SNAP_BROAD_ROUNDTRIP_EXCEPTION_ENABLED:-1}"
export PGG2_LIVE_PRICED_SNAP_BROAD_MIN_BUY1500="${PGG2_LIVE_PRICED_SNAP_BROAD_MIN_BUY1500:-10.5}"
export PGG2_LIVE_PRICED_SNAP_BROAD_MIN_UNIQ1500="${PGG2_LIVE_PRICED_SNAP_BROAD_MIN_UNIQ1500:-9}"
export PGG2_LIVE_PRICED_SNAP_BROAD_MAX_TOP1500="${PGG2_LIVE_PRICED_SNAP_BROAD_MAX_TOP1500:-0.35}"
export PGG2_LIVE_PRICED_SNAP_BROAD_MAX_SELL_RATIO1500="${PGG2_LIVE_PRICED_SNAP_BROAD_MAX_SELL_RATIO1500:-0.015}"
export PGG2_LIVE_PRICED_SNAP_BROAD_MAX_ENTRY_MOVE="${PGG2_LIVE_PRICED_SNAP_BROAD_MAX_ENTRY_MOVE:-1.25}"
export PGG2_LIVE_PRICED_SNAP_BROAD_MAX_AGE_MS="${PGG2_LIVE_PRICED_SNAP_BROAD_MAX_AGE_MS:-900}"
export PGG2_LIVE_PRICED_SNAP_BROAD_MAX_ROUNDTRIP_LOSS_RATIO="${PGG2_LIVE_PRICED_SNAP_BROAD_MAX_ROUNDTRIP_LOSS_RATIO:-0.050}"
export PGG2_LIVE_PRICED_SNAP_BROAD_ROUNDTRIP_ABS_FLOOR_SOL="${PGG2_LIVE_PRICED_SNAP_BROAD_ROUNDTRIP_ABS_FLOOR_SOL:-0.00200}"
export PGG2_DIRECT_SELECT_BUYBACK_BY_SIM=0
export PGG2_DIRECT_REQUIRE_SIM_SELECTED_BUYBACK=0
export PGG2_DIRECT_OBSERVED_PAIR_FROM_RAW=1
export PGG2_DIRECT_OBSERVED_PAIR_MAX_SIGS="${PGG2_DIRECT_OBSERVED_PAIR_MAX_SIGS:-10}"
export PGG2_DIRECT_OBSERVED_PAIR_TAIL_BYTES="${PGG2_DIRECT_OBSERVED_PAIR_TAIL_BYTES:-8388608}"
export PGG2_DIRECT_PUMP_REMAINING_CACHE="${PGG2_DIRECT_PUMP_REMAINING_CACHE:-/root/piggy/data/pgg2_pump_remaining_cache.json}"
export PGG2_DIRECT_REQUIRE_OBSERVED_BUYBACK_PAIR=1
export PGG2_DIRECT_ACCOUNT_COMMITMENT=processed
export PGG2_DIRECT_BLOCKHASH_COMMITMENT=processed
export PGG2_DIRECT_CURVE_ACCOUNT_TTL_SEC=0

# Experimentalji 2026-05-07 loss patch: keep entry scanning aggressive, but
# reject stale priced-snap entries where the 1500ms cluster is no longer alive,
# and cap priced-snap executable losses from direct sell quotes.
export PGG2_PRICED_SNAP_REQUIRE_LIVE700_ENABLED="${PGG2_PRICED_SNAP_REQUIRE_LIVE700_ENABLED:-1}"
export PGG2_PRICED_SNAP_SOL="${PGG2_PRICED_SNAP_SOL:-0.015}"
export PGG2_PRICED_SNAP_MAX_SELL_RATIO1500="${PGG2_PRICED_SNAP_MAX_SELL_RATIO1500:-0.010}"
export PGG2_PRICED_SNAP_MIN_LIVE_BUY700="${PGG2_PRICED_SNAP_MIN_LIVE_BUY700:-3.0}"
export PGG2_PRICED_SNAP_MIN_LIVE_UNIQ700="${PGG2_PRICED_SNAP_MIN_LIVE_UNIQ700:-4}"
export PGG2_PRICED_SNAP_MAX_LIVE_TOP700="${PGG2_PRICED_SNAP_MAX_LIVE_TOP700:-0.72}"
export PGG2_PRICED_SNAP_STALE_LIVE700_BROAD1500_OVERRIDE_ENABLED="${PGG2_PRICED_SNAP_STALE_LIVE700_BROAD1500_OVERRIDE_ENABLED:-1}"
export PGG2_PRICED_SNAP_STALE_LIVE700_MIN_BUY1500="${PGG2_PRICED_SNAP_STALE_LIVE700_MIN_BUY1500:-24.0}"
export PGG2_PRICED_SNAP_STALE_LIVE700_MIN_UNIQ1500="${PGG2_PRICED_SNAP_STALE_LIVE700_MIN_UNIQ1500:-10}"
export PGG2_PRICED_SNAP_STALE_LIVE700_MAX_TOP1500="${PGG2_PRICED_SNAP_STALE_LIVE700_MAX_TOP1500:-0.22}"
export PGG2_PRICED_SNAP_STALE_LIVE700_MAX_SELL_RATIO1500="${PGG2_PRICED_SNAP_STALE_LIVE700_MAX_SELL_RATIO1500:-0.01}"
export PGG2_PRICED_SNAP_STALE_LIVE700_MIN_ENTRY_MOVE="${PGG2_PRICED_SNAP_STALE_LIVE700_MIN_ENTRY_MOVE:-1.35}"
export PGG2_PRICED_SNAP_STALE_LIVE700_MAX_ENTRY_MOVE="${PGG2_PRICED_SNAP_STALE_LIVE700_MAX_ENTRY_MOVE:-1.56}"
export PGG2_PRICED_SNAP_STALE_LIVE700_MIN_VSOL="${PGG2_PRICED_SNAP_STALE_LIVE700_MIN_VSOL:-35.0}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_LOSS_CLAMP_ENABLED="${PGG2_PRICED_SNAP_EXEC_QUOTE_LOSS_CLAMP_ENABLED:-1}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_CLAMP_MIN_AGE_SEC="${PGG2_PRICED_SNAP_EXEC_QUOTE_CLAMP_MIN_AGE_SEC:-0.45}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_CLAMP_INTERVAL_MS="${PGG2_PRICED_SNAP_EXEC_QUOTE_CLAMP_INTERVAL_MS:-300}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_RECOVERY_GRACE_SEC="${PGG2_PRICED_SNAP_EXEC_QUOTE_RECOVERY_GRACE_SEC:-3.25}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_RECOVERY_MIN_PEAK="${PGG2_PRICED_SNAP_EXEC_QUOTE_RECOVERY_MIN_PEAK:-1.25}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_MIN_CHECKS_BEFORE_CUT="${PGG2_PRICED_SNAP_EXEC_QUOTE_MIN_CHECKS_BEFORE_CUT:-2}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_IMPROVE_EPS_SOL="${PGG2_PRICED_SNAP_EXEC_QUOTE_IMPROVE_EPS_SOL:-0.00035}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_PANIC_LOSS_SOL="${PGG2_PRICED_SNAP_EXEC_QUOTE_PANIC_LOSS_SOL:-0.0060}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_PANIC_MULT="${PGG2_PRICED_SNAP_EXEC_QUOTE_PANIC_MULT:-0.74}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_ENABLED="${PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_ENABLED:-1}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_MIN_BEST_SOL="${PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_MIN_BEST_SOL:-0.00150}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_MIN_CHECKS="${PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_MIN_CHECKS:-2}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_KEEP_RATIO="${PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_KEEP_RATIO:-0.25}"
export PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_MIN_LOCK_SOL="${PGG2_PRICED_SNAP_EXEC_QUOTE_PROFIT_TRAIL_MIN_LOCK_SOL:-0.00025}"
export PGG2_LIVE_PRICED_SNAP_MAX_EXECUTABLE_LOSS_RATIO="${PGG2_LIVE_PRICED_SNAP_MAX_EXECUTABLE_LOSS_RATIO:-0.040}"
export PGG2_LIVE_PRICED_SNAP_MAX_EXECUTABLE_LOSS_FLOOR_SOL="${PGG2_LIVE_PRICED_SNAP_MAX_EXECUTABLE_LOSS_FLOOR_SOL:-0.00125}"
export PGG2_LIVE_PRICED_SNAP_MAX_EXECUTABLE_LOSS_CAP_SOL="${PGG2_LIVE_PRICED_SNAP_MAX_EXECUTABLE_LOSS_CAP_SOL:-0.00160}"
export PGG2_LIVE_PRICED_SNAP_RUNNER_RECOVERY_EXCEPTION_ENABLED="${PGG2_LIVE_PRICED_SNAP_RUNNER_RECOVERY_EXCEPTION_ENABLED:-1}"
export PGG2_LIVE_PRICED_SNAP_RUNNER_MAX_EXECUTABLE_LOSS_CAP_SOL="${PGG2_LIVE_PRICED_SNAP_RUNNER_MAX_EXECUTABLE_LOSS_CAP_SOL:-0.00350}"
export PGG2_PRICED_SNAP_LATE_FLAT_SKIP_ENABLED="${PGG2_PRICED_SNAP_LATE_FLAT_SKIP_ENABLED:-1}"
export PGG2_PRICED_SNAP_LATE_FLAT_MIN_ENTRY_MOVE="${PGG2_PRICED_SNAP_LATE_FLAT_MIN_ENTRY_MOVE:-1.58}"
export PGG2_PRICED_SNAP_LATE_FLAT_MAX_MOVE700="${PGG2_PRICED_SNAP_LATE_FLAT_MAX_MOVE700:-1.04}"
export PGG2_PRICED_SNAP_LATE_FLAT_MAX_SLOT_BUYERS="${PGG2_PRICED_SNAP_LATE_FLAT_MAX_SLOT_BUYERS:-3}"
export PGG2_PRICED_SNAP_LATE_FLAT_MIN_SLOT_TOP="${PGG2_PRICED_SNAP_LATE_FLAT_MIN_SLOT_TOP:-0.55}"
export PGG2_PRICED_SNAP_LATE_FLAT_MAX_BUY1500="${PGG2_PRICED_SNAP_LATE_FLAT_MAX_BUY1500:-10.5}"
export PGG2_LIVE_REUSE_EXIT_QUOTE_ENABLED="${PGG2_LIVE_REUSE_EXIT_QUOTE_ENABLED:-1}"
export PGG2_LIVE_REUSE_EXIT_QUOTE_MAX_AGE_MS="${PGG2_LIVE_REUSE_EXIT_QUOTE_MAX_AGE_MS:-700}"
export PGG2_LIVE_CURVE_LAG_THIN_MAX_ROUNDTRIP_LOSS_RATIO="${PGG2_LIVE_CURVE_LAG_THIN_MAX_ROUNDTRIP_LOSS_RATIO:-0.040}"
export PGG2_LIVE_CURVE_LAG_THIN_ROUNDTRIP_ABS_FLOOR_SOL="${PGG2_LIVE_CURVE_LAG_THIN_ROUNDTRIP_ABS_FLOOR_SOL:-0.00125}"
export PGG2_LIVE_CURVE_LAG_THIN_MAX_EXECUTABLE_LOSS_RATIO="${PGG2_LIVE_CURVE_LAG_THIN_MAX_EXECUTABLE_LOSS_RATIO:-0.040}"
export PGG2_LIVE_CURVE_LAG_THIN_MAX_EXECUTABLE_LOSS_FLOOR_SOL="${PGG2_LIVE_CURVE_LAG_THIN_MAX_EXECUTABLE_LOSS_FLOOR_SOL:-0.00125}"
export PGG2_LIVE_CURVE_LAG_THIN_MAX_EXECUTABLE_LOSS_CAP_SOL="${PGG2_LIVE_CURVE_LAG_THIN_MAX_EXECUTABLE_LOSS_CAP_SOL:-0.00125}"
export PGG2_LIVE_CURVE_LAG_THIN_STALL_EXIT_ENABLED="${PGG2_LIVE_CURVE_LAG_THIN_STALL_EXIT_ENABLED:-1}"
export PGG2_LIVE_CURVE_LAG_THIN_STALL_EXIT_AFTER_SEC="${PGG2_LIVE_CURVE_LAG_THIN_STALL_EXIT_AFTER_SEC:-0.75}"
export PGG2_LIVE_CURVE_LAG_THIN_STALL_EXIT_MAX_PNL_SOL="${PGG2_LIVE_CURVE_LAG_THIN_STALL_EXIT_MAX_PNL_SOL:-0.00005}"
export PGG2_LIVE_RUNNER_AFTER_GREEN_ENABLED="${PGG2_LIVE_RUNNER_AFTER_GREEN_ENABLED:-1}"
export PGG2_LIVE_RUNNER_AFTER_GREEN_LANES="${PGG2_LIVE_RUNNER_AFTER_GREEN_LANES:-raw_momentum,priced_snap}"
export PGG2_LIVE_RUNNER_BANK_SELL_FRACTION="${PGG2_LIVE_RUNNER_BANK_SELL_FRACTION:-0.90}"
export PGG2_LIVE_RUNNER_BANK_MIN_FULL_PNL_SOL="${PGG2_LIVE_RUNNER_BANK_MIN_FULL_PNL_SOL:-0.00075}"
export PGG2_LIVE_RUNNER_BANK_MIN_LOCKED_PNL_SOL="${PGG2_LIVE_RUNNER_BANK_MIN_LOCKED_PNL_SOL:-0.00020}"
export PGG2_LIVE_RUNNER_MIN_CLOSE_PNL_SOL="${PGG2_LIVE_RUNNER_MIN_CLOSE_PNL_SOL:-0.00020}"
export PGG2_LIVE_RUNNER_SUPPRESS_ANY_PROFIT_BANK="${PGG2_LIVE_RUNNER_SUPPRESS_ANY_PROFIT_BANK:-1}"
export PGG2_LIVE_RUNNER_SUPPRESS_PROFIT_BANK="${PGG2_LIVE_RUNNER_SUPPRESS_PROFIT_BANK:-1}"
export PGG2_QUOTE_PARTIAL_SELL_OVERHEAD_SOL="${PGG2_QUOTE_PARTIAL_SELL_OVERHEAD_SOL:-0.00065}"

# Existing blind-spot lane, now enabled only with tight live-700 breadth.
# Fast scan on the current multi-source tape: this catches clean missed runners
# (HLen, 7XkS) while excluding the candidate that dipped to 0.81x before running.
export PGG2_RAW_MOMENTUM_ENABLED=1
export PGG2_RAW_MOMENTUM_SOL="${PGG2_RAW_MOMENTUM_SOL:-0.040}"
export PGG2_RAW_MOMENTUM_CONFIRM_MIN_UNIQ700="${PGG2_RAW_MOMENTUM_CONFIRM_MIN_UNIQ700:-7}"
export PGG2_RAW_MOMENTUM_CONFIRM_MAX_TOP700="${PGG2_RAW_MOMENTUM_CONFIRM_MAX_TOP700:-0.34}"
export PGG2_LIVE_BREADTH_BREAKOUT_ENABLED="${PGG2_LIVE_BREADTH_BREAKOUT_ENABLED:-1}"
export PGG2_LIVE_BREADTH_BREAKOUT_MIN_ENTRY_MOVE="${PGG2_LIVE_BREADTH_BREAKOUT_MIN_ENTRY_MOVE:-1.45}"
export PGG2_LIVE_BREADTH_BREAKOUT_MAX_ENTRY_MOVE="${PGG2_LIVE_BREADTH_BREAKOUT_MAX_ENTRY_MOVE:-1.56}"
export PGG2_LIVE_BREADTH_BREAKOUT_MIN_VSOL="${PGG2_LIVE_BREADTH_BREAKOUT_MIN_VSOL:-45.0}"
export PGG2_LIVE_BREADTH_BREAKOUT_MIN_BUY700="${PGG2_LIVE_BREADTH_BREAKOUT_MIN_BUY700:-7.0}"
export PGG2_LIVE_BREADTH_BREAKOUT_MIN_UNIQ700="${PGG2_LIVE_BREADTH_BREAKOUT_MIN_UNIQ700:-6}"
export PGG2_LIVE_BREADTH_BREAKOUT_MAX_TOP700="${PGG2_LIVE_BREADTH_BREAKOUT_MAX_TOP700:-0.30}"
export PGG2_LIVE_BREADTH_BREAKOUT_MIN_BUY1500="${PGG2_LIVE_BREADTH_BREAKOUT_MIN_BUY1500:-8.0}"
export PGG2_LIVE_BREADTH_BREAKOUT_MIN_UNIQ1500="${PGG2_LIVE_BREADTH_BREAKOUT_MIN_UNIQ1500:-7}"
export PGG2_LIVE_BREADTH_BREAKOUT_MAX_TOP1500="${PGG2_LIVE_BREADTH_BREAKOUT_MAX_TOP1500:-0.22}"
export PGG2_LIVE_BREADTH_BREAKOUT_MAX_SELL_RATIO1500="${PGG2_LIVE_BREADTH_BREAKOUT_MAX_SELL_RATIO1500:-0.03}"
export PGG2_EXEC_SPIKE_PROBE_ENABLED="${PGG2_EXEC_SPIKE_PROBE_ENABLED:-1}"
export PGG2_EXEC_SPIKE_PROBE_SOL="${PGG2_EXEC_SPIKE_PROBE_SOL:-0.015}"
export PGG2_EXEC_SPIKE_PROBE_MIN_AGE_SEC="${PGG2_EXEC_SPIKE_PROBE_MIN_AGE_SEC:-3.0}"
export PGG2_EXEC_SPIKE_PROBE_MIN_ENTRY_MOVE="${PGG2_EXEC_SPIKE_PROBE_MIN_ENTRY_MOVE:-1.70}"
export PGG2_EXEC_SPIKE_PROBE_MAX_ENTRY_MOVE="${PGG2_EXEC_SPIKE_PROBE_MAX_ENTRY_MOVE:-3.50}"
export PGG2_EXEC_SPIKE_PROBE_MAX_AGE_SEC="${PGG2_EXEC_SPIKE_PROBE_MAX_AGE_SEC:-60.0}"
export PGG2_EXEC_SPIKE_PROBE_MIN_VSOL="${PGG2_EXEC_SPIKE_PROBE_MIN_VSOL:-30.0}"
export PGG2_EXEC_SPIKE_PROBE_MAX_VSOL="${PGG2_EXEC_SPIKE_PROBE_MAX_VSOL:-125.0}"
export PGG2_EXEC_SPIKE_PROBE_MIN_CURRENT_BUY_SOL="${PGG2_EXEC_SPIKE_PROBE_MIN_CURRENT_BUY_SOL:-0.008}"
export PGG2_EXEC_SPIKE_PROBE_MAX_CURRENT_BUY_SOL="${PGG2_EXEC_SPIKE_PROBE_MAX_CURRENT_BUY_SOL:-0.55}"
export PGG2_EXEC_SPIKE_PROBE_MAX_SELL_RATIO1500="${PGG2_EXEC_SPIKE_PROBE_MAX_SELL_RATIO1500:-0.08}"
export PGG2_EXEC_SPIKE_PROBE_MAX_LAST_BUY_MS="${PGG2_EXEC_SPIKE_PROBE_MAX_LAST_BUY_MS:-500}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_ENABLED="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_ENABLED:-1}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MIN_AGE_SEC="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MIN_AGE_SEC:-8.0}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_AGE_SEC="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_AGE_SEC:-75.0}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MIN_ENTRY_MOVE="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MIN_ENTRY_MOVE:-2.0}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_ENTRY_MOVE="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_ENTRY_MOVE:-3.2}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MIN_VSOL="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MIN_VSOL:-55.0}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_VSOL="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_VSOL:-125.0}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MIN_CURRENT_BUY_SOL="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MIN_CURRENT_BUY_SOL:-0.75}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_CURRENT_BUY_SOL="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_CURRENT_BUY_SOL:-2.50}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_SELL_RATIO1500="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_SELL_RATIO1500:-0.08}"
export PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_LAST_BUY_MS="${PGG2_EXEC_SPIKE_LATE_BIG_BUY_MAX_LAST_BUY_MS:-500}"
export PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_EXCEPTION_ENABLED="${PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_EXCEPTION_ENABLED:-1}"
export PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_MIN_VSOL="${PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_MIN_VSOL:-40.0}"
export PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_ROUNDTRIP_ABS_FLOOR_SOL="${PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_ROUNDTRIP_ABS_FLOOR_SOL:-0.00320}"
export PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_MAX_EXECUTABLE_LOSS_RATIO="${PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_MAX_EXECUTABLE_LOSS_RATIO:-0.10}"
export PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_MAX_EXECUTABLE_LOSS_CAP_SOL="${PGG2_LIVE_RAW_EXEC_SPIKE_RUNNER_MAX_EXECUTABLE_LOSS_CAP_SOL:-0.00160}"
export PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CHASE_ENABLED="${PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CHASE_ENABLED:-1}"
export PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CHASE_MAX_SEC="${PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CHASE_MAX_SEC:-8.0}"
export PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CHASE_INTERVAL_MS="${PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CHASE_INTERVAL_MS:-350}"
export PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CHASE_MAX_ATTEMPTS="${PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CHASE_MAX_ATTEMPTS:-12}"
export PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CONFIRMATIONS="${PGG2_LIVE_RAW_EXEC_SPIKE_GREEN_CONFIRMATIONS:-2}"
export PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_RUNNER_ENABLED="${PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_RUNNER_ENABLED:-1}"
export PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MIN_PNL_SOL="${PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MIN_PNL_SOL:-0.00150}"
export PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MIN_ENTRY_MOVE="${PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MIN_ENTRY_MOVE:-2.30}"
export PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MAX_ENTRY_MOVE="${PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MAX_ENTRY_MOVE:-3.50}"
export PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MIN_VSOL="${PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MIN_VSOL:-65.0}"
export PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MAX_SELL1500="${PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MAX_SELL1500:-0.001}"
export PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MAX_ATTEMPT="${PGG2_LIVE_RAW_EXEC_SPIKE_ONE_GREEN_MAX_ATTEMPT:-6}"
export PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_RUNNER_ENABLED="${PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_RUNNER_ENABLED:-1}"
export PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MIN_PNL_SOL="${PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MIN_PNL_SOL:--0.00110}"
export PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MIN_ENTRY_MOVE="${PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MIN_ENTRY_MOVE:-2.30}"
export PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MAX_ENTRY_MOVE="${PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MAX_ENTRY_MOVE:-3.10}"
export PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MIN_VSOL="${PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MIN_VSOL:-60.0}"
export PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MAX_SELL1500="${PGG2_LIVE_RAW_EXEC_SPIKE_TINY_RED_MAX_SELL1500:-0.001}"
export PGG2_LIVE_ALLOW_FAST_REENTRY_AFTER_DIRECT_RUNNER_CLOSE="${PGG2_LIVE_ALLOW_FAST_REENTRY_AFTER_DIRECT_RUNNER_CLOSE:-1}"
export PGG2_RUNNER_REENTRY_UNLOCK_ENABLED="${PGG2_RUNNER_REENTRY_UNLOCK_ENABLED:-1}"
export PGG2_RUNNER_REENTRY_UNLOCK_MAX_LOSS_SOL="${PGG2_RUNNER_REENTRY_UNLOCK_MAX_LOSS_SOL:-0.00165}"
export PGG2_RUNNER_REENTRY_UNLOCK_MAX_WIN_SOL="${PGG2_RUNNER_REENTRY_UNLOCK_MAX_WIN_SOL:-0.00800}"
export PGG2_LIVE_RAW_EXEC_SPIKE_ANY_PROFIT_BANK_MIN_PNL_SOL="${PGG2_LIVE_RAW_EXEC_SPIKE_ANY_PROFIT_BANK_MIN_PNL_SOL:-0.00045}"

# Experimental source router. Pump/PumpSwap are direct-builder capable.
# LaunchLab and DBC are captured as live-market evidence until venue-specific
# execution proves exact cost/route parity.
export EXPERIMENTALJI_MULTI_SOURCE=1
export EXPERIMENTALJI_ENABLE_PUMPSWAP_SOURCE="${EXPERIMENTALJI_ENABLE_PUMPSWAP_SOURCE:-1}"
export EXPERIMENTALJI_TRADE_PUMPSWAP_SOURCE="${EXPERIMENTALJI_TRADE_PUMPSWAP_SOURCE:-1}"
export EXPERIMENTALJI_ENABLE_LAUNCHLAB_SOURCE="${EXPERIMENTALJI_ENABLE_LAUNCHLAB_SOURCE:-1}"
export EXPERIMENTALJI_TRADE_LAUNCHLAB_SOURCE="${EXPERIMENTALJI_TRADE_LAUNCHLAB_SOURCE:-0}"
export EXPERIMENTALJI_ENABLE_DBC_SOURCE="${EXPERIMENTALJI_ENABLE_DBC_SOURCE:-1}"
export EXPERIMENTALJI_TRADE_DBC_SOURCE="${EXPERIMENTALJI_TRADE_DBC_SOURCE:-0}"
export EXPERIMENTALJI_SOURCE_PRICE_HINTS="${EXPERIMENTALJI_SOURCE_PRICE_HINTS:-1}"
export EXPERIMENTALJI_STATUS_SOURCE_SUMMARY="${EXPERIMENTALJI_STATUS_SOURCE_SUMMARY:-1}"
export EXPERIMENTALJI_OBSERVATIONS_FILE="/root/piggy/data/${RUNID}_source_observations.jsonl"

echo "EXPERIMENTALJI_RUN_ID=${RUNID}"
echo "EXPERIMENTALJI_LOG=/root/piggy/logs/${RUNID}.log"
echo "EXPERIMENTALJI_MODE=QUOTE_DIRECT_DRYLIVE_MULTI_SOURCE"

exec ./venv/bin/python -u experimentalji.py 2>&1 | tee "/root/piggy/logs/${RUNID}.log"
