#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# v39b one-entry real-live smoke launcher.
# This mirrors start_pgg2_v39b_quote_rescue_drylive.sh except for the
# approved live/smoke controls below. Do not use this until
# compare_v39b_drylive_vs_live_env.py and the live precheck pass.

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_v39b_quote_rescue_live_smoke}"

export PGG2_EXECUTION_MODE=live
export PGG2_ENABLE_LIVE=1
export PIGGY_PAPER_TRADING=0
export PGG2_DRY_LIVE_MODE=0
export PGG2_LIVE_BROKER=direct_pump
export PGG2_WALLET_KEYPAIR="${PGG2_WALLET_KEYPAIR:-/root/piggy/live_wallet.key}"
export PGG2_LIVE_CONFIRM="${PGG2_LIVE_CONFIRM:-I_ACCEPT_REAL_SOL_RISK}"
export PGG2_DIRECT_LIVE_CONFIRM="${PGG2_DIRECT_LIVE_CONFIRM:-I_ACCEPT_DIRECT_PUMP_RISK}"
export PGG2_LIVE_SMOKE_MAX_ENTRIES=1
export PGG2_DRYLIVE_OR_LIVE_MAX_ENTRIES=1

export PGG2_QUOTE_SHADOW_POSITIONS=0
export PGG2_QUOTE_SIMULATE=0
export PGG2_LIVE_SIMULATE_BEFORE_SEND=0
export PGG2_LIVE_SKIP_PREFLIGHT=1
export PGG2_LIVE_PREFLIGHT_ROUNDTRIP_ENABLED=0
export PGG2_LIVE_FINAL_ENTRY_GUARD_ENABLED=0
export PGG2_DIRECT_SELECT_BUYBACK_BY_SIM=0
export PGG2_DIRECT_REQUIRE_SIM_SELECTED_BUYBACK=0
export PGG2_DIRECT_OBSERVED_PAIR_FROM_RAW=1
export PGG2_DIRECT_REQUIRE_OBSERVED_BUYBACK_PAIR=1
export PGG2_DIRECT_ACCOUNT_COMMITMENT=processed
export PGG2_DIRECT_BLOCKHASH_COMMITMENT=processed
export PGG2_DIRECT_CURVE_ACCOUNT_TTL_SEC=0
export PGG2_DIRECT_EXIT_ANY_EXECUTABLE_PRICE=1
export PGG2_DIRECT_EXIT_MIN_LAMPORTS=1

export PGG2_V39_LEAD_TIME_SCALP_ENABLED=1
export PGG2_V39_ONLINE_LEAD_CAPTURE_ENABLED=1
export PGG2_V39_DRYLIVE_ACTUAL_ENTRY_ENABLED=1
export PGG2_V39_LIVE_SMOKE_ENABLED=1
export PGG2_V39_QUOTE_RESCUE_ENABLED=1
export PGG2_ACTUAL_ENTRY_MASTER_ENABLED=1
export PGG2_V39_TARGET_ENTRIES=1
export PGG2_V39_MAX_OPEN=1
export PIGGY_MAX_OPEN=1
export PIGGY_MAX_OPEN_POSITIONS=1
export PGG2_V39_LEAD_SNAPSHOT_MS="${PGG2_V39_LEAD_SNAPSHOT_MS:-0,100,250,500,750,1000,1500,2000,3000}"
export PGG2_V39_ENTRY_MIN_PROCESSED_PNL_SOL="${PGG2_V39_ENTRY_MIN_PROCESSED_PNL_SOL:-0.00020}"
export PGG2_V39_BANK_PNL_SOL="${PGG2_V39_BANK_PNL_SOL:-0.00060}"
export PGG2_V39_SCRATCH_PNL_SOL="${PGG2_V39_SCRATCH_PNL_SOL:-0.00005}"
export PGG2_V39_CLAMP_LOSS_SOL="${PGG2_V39_CLAMP_LOSS_SOL:-0.00050}"
export PGG2_V39_MAX_HOLD_MS="${PGG2_V39_MAX_HOLD_MS:-3000}"
export PGG2_V39_ABSOLUTE_MAX_HOLD_MS="${PGG2_V39_ABSOLUTE_MAX_HOLD_MS:-5000}"
export PGG2_V39_MAX_SELL_LATENCY_MS="${PGG2_V39_MAX_SELL_LATENCY_MS:-750}"
# Loss isolation from v39b-1: late quote-gradient entries can deteriorate
# before the risk worker close executes. Keep high-edge rules unrestricted,
# but require quote-gradient evidence to resolve by 1500ms.
export PGG2_V39_QUOTE_GRADIENT_MAX_DELAY_MS="${PGG2_V39_QUOTE_GRADIENT_MAX_DELAY_MS:-1500}"

# Quote rescue: prefetch sell quotes for hot v39 mints. Entry may use only a
# fresh amount-compatible prefetched quote. One in-flight sell per mint/side is
# enforced inside QuoteManager.
export PGG2_V39_PREFETCH_INTERVAL_MS="${PGG2_V39_PREFETCH_INTERVAL_MS:-300}"
export PGG2_V39_PREFETCH_TTL_MS="${PGG2_V39_PREFETCH_TTL_MS:-500}"
export PGG2_V39_WATCHLIST_MAX_MS="${PGG2_V39_WATCHLIST_MAX_MS:-5000}"
export PGG2_V39_PREFETCH_AMOUNT_TOL_PCT="${PGG2_V39_PREFETCH_AMOUNT_TOL_PCT:-0.50}"
export PGG2_V39_PREFETCH_TRIGGER_ENTRY_ENABLED="${PGG2_V39_PREFETCH_TRIGGER_ENTRY_ENABLED:-1}"
export PGG2_V39_PREFETCH_BUY_QUOTE_MAX_AGE_MS="${PGG2_V39_PREFETCH_BUY_QUOTE_MAX_AGE_MS:-1500}"
export PGG2_QUOTE_MGR_CACHE_TTL_MS="${PGG2_QUOTE_MGR_CACHE_TTL_MS:-500}"
export PGG2_QUOTE_MGR_REFRESH_AFTER_MS="${PGG2_QUOTE_MGR_REFRESH_AFTER_MS:-250}"

export PGG2_DRYLIVE_PILOT_ENABLED=0
export PGG2_SCALP_ENABLED=0
export PGG2_SHADOW_LAB_CANARY_ACTUAL_ENTRY=0
export PGG2_ENTRY_SNAPSHOT_BANK_ENABLED=0
export PGG2_ENTRY_SNAPSHOT_BANK_LIVE_ELIGIBLE=0

export PGG2_SHADOW_LAB_ENABLED=1
export PGG2_SHADOW_OBSERVE_ENABLED=1
export PGG2_SHADOW_LAB_MAX_CONCURRENT="${PGG2_SHADOW_LAB_MAX_CONCURRENT:-8}"
export PGG2_SHADOW_LAB_COOLDOWN_MS="${PGG2_SHADOW_LAB_COOLDOWN_MS:-12000}"
export PGG2_SHADOW_OBSERVE_MIN_SOL_V39_LEAD="${PGG2_SHADOW_OBSERVE_MIN_SOL_V39_LEAD:-0.0}"
# v39 online lead snapshots replace the old shadow future-sell/delayed-entry
# diagnostic loops for this run. Disabling those loops prevents them from
# racing the rescue prefetcher on the same mint/side.
export PGG2_SHADOW_LAB_SELL_DELAYS_MS="${PGG2_SHADOW_LAB_SELL_DELAYS_MS:-}"
export PGG2_SHADOW_DELAYED_ENTRY_SCANNER=0
export PGG2_V39_LEAD_MIN_BUY_SOL_700="${PGG2_V39_LEAD_MIN_BUY_SOL_700:-0.70}"
export PGG2_V39_LEAD_MIN_BUYERS_700="${PGG2_V39_LEAD_MIN_BUYERS_700:-1}"
export PGG2_V39_LEAD_MAX_TOP_SHARE_700="${PGG2_V39_LEAD_MAX_TOP_SHARE_700:-1.0}"
export PGG2_V39_LEAD_MAX_SELL_RATIO_700="${PGG2_V39_LEAD_MAX_SELL_RATIO_700:-0.35}"

export PGG2_RISK_WORKER_ENABLED=1
export PGG2_RISK_WORKER_OWNS_QUOTE_EXIT=1
export PGG2_RISK_ALLOW_OVERLAP_QUOTES=0

export PGG2_LIVE_BUY_SLIPPAGE_PCT="${PGG2_LIVE_BUY_SLIPPAGE_PCT:-65}"
export PGG2_LIVE_SELL_SLIPPAGE_PCT="${PGG2_LIVE_SELL_SLIPPAGE_PCT:-99}"
export PGG2_LIVE_MAX_TRADE_SOL=0.015
export PGG2_LIVE_MIN_TRADE_SOL=0.015
export PGG2_LIVE_MIN_WALLET_RESERVE_SOL="${PGG2_LIVE_MIN_WALLET_RESERVE_SOL:-0.080}"
export PGG2_LIVE_MAX_SESSION_LOSS_SOL=999
export PGG2_LIVE_MAX_CONSECUTIVE_LOSSES=999

echo "PGG2-LIVE-SMOKE-START run_prefix=${PGG2_RUN_PREFIX} max_entries=${PGG2_V39_TARGET_ENTRIES} max_open=${PGG2_V39_MAX_OPEN}"
exec ./start_pgg2_attack_paper.sh
