#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# v39b live mirror of the successful dry-live launcher:
# start_pgg2_v39b_quote_rescue_drylive.sh
# Successful dry-live reference:
# logs/pgg2_v39b_quote_rescue_drylive_20260512_133527.log
# 10W/0L, v39 net +0.037966 SOL, status realized_all_in +0.039067 SOL.
#
# Strategy gates and thresholds intentionally match the successful dry-live
# launcher. Differences are live execution plumbing only.

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_v39b_quote_rescue_live_mirror}"

export PGG2_EXECUTION_MODE=live
export PGG2_ENABLE_LIVE=1
export PIGGY_PAPER_TRADING=0
export PGG2_DRY_LIVE_MODE=0
export PGG2_LIVE_BROKER=direct_pump
export PGG2_WALLET_KEYPAIR="${PGG2_WALLET_KEYPAIR:-/root/piggy/live_wallet.key}"
export PGG2_LIVE_CONFIRM="${PGG2_LIVE_CONFIRM:-I_ACCEPT_REAL_SOL_RISK}"
export PGG2_DIRECT_LIVE_CONFIRM="${PGG2_DIRECT_LIVE_CONFIRM:-I_ACCEPT_DIRECT_PUMP_RISK}"

export PGG2_QUOTE_SHADOW_POSITIONS=0
export PGG2_QUOTE_SIMULATE=0
export PGG2_LIVE_SIMULATE_BEFORE_SEND=0
export PGG2_LIVE_SKIP_PREFLIGHT=1
export PGG2_LIVE_SEND_MODE="${PGG2_LIVE_SEND_MODE:-jito_low_latency}"
export PGG2_JITO_ENABLED="${PGG2_JITO_ENABLED:-1}"
export PGG2_JITO_BLOCK_ENGINE_URL="${PGG2_JITO_BLOCK_ENGINE_URL:-https://mainnet.block-engine.jito.wtf}"
export PGG2_JITO_MAX_TIP_LAMPORTS="${PGG2_JITO_MAX_TIP_LAMPORTS:-25000}"
export PGG2_JITO_MIN_TIP_LAMPORTS="${PGG2_JITO_MIN_TIP_LAMPORTS:-1000}"
export PGG2_JITO_TIP_POLICY="${PGG2_JITO_TIP_POLICY:-edge_capped}"
export PGG2_JITO_TIP_EDGE_FRACTION="${PGG2_JITO_TIP_EDGE_FRACTION:-0.25}"
export PGG2_JITO_MAX_TIP_FRACTION_OF_EDGE="${PGG2_JITO_MAX_TIP_FRACTION_OF_EDGE:-0.25}"
export PGG2_JITO_SUBMIT_METHOD="${PGG2_JITO_SUBMIT_METHOD:-transaction}"
export PGG2_LIVE_PREFLIGHT_ROUNDTRIP_ENABLED=0
export PGG2_LIVE_FINAL_ENTRY_GUARD_ENABLED=0
export PGG2_DIRECT_SELECT_BUYBACK_BY_SIM=0
export PGG2_DIRECT_REQUIRE_SIM_SELECTED_BUYBACK=0
export PGG2_DIRECT_OBSERVED_PAIR_FROM_RAW=1
export PGG2_DIRECT_REQUIRE_OBSERVED_BUYBACK_PAIR=1
export PGG2_DIRECT_ACCOUNT_COMMITMENT=processed
export PGG2_DIRECT_BLOCKHASH_COMMITMENT=processed
export PGG2_DIRECT_CURVE_ACCOUNT_TTL_SEC=0
export PGG2_DIRECT_EXIT_ANY_EXECUTABLE_PRICE=1
export PGG2_DIRECT_EXIT_MIN_LAMPORTS=1

export PGG2_V39_LEAD_TIME_SCALP_ENABLED=1
export PGG2_V39_ONLINE_LEAD_CAPTURE_ENABLED=1
export PGG2_V39_DRYLIVE_ACTUAL_ENTRY_ENABLED=1
export PGG2_V39_LIVE_MIRROR_ENABLED=1
export PGG2_V39_QUOTE_RESCUE_ENABLED=1
export PGG2_ACTUAL_ENTRY_MASTER_ENABLED=1
export PGG2_V39_TARGET_ENTRIES="${PGG2_V39_TARGET_ENTRIES:-10}"
export PGG2_V39_MAX_OPEN="${PGG2_V39_MAX_OPEN:-5}"
export PIGGY_MAX_OPEN="${PIGGY_MAX_OPEN:-$PGG2_V39_MAX_OPEN}"
export PIGGY_MAX_OPEN_POSITIONS="${PIGGY_MAX_OPEN_POSITIONS:-$PGG2_V39_MAX_OPEN}"
export PGG2_V39_LEAD_SNAPSHOT_MS="${PGG2_V39_LEAD_SNAPSHOT_MS:-0,100,250,500,750,1000,1500,2000,3000}"
export PGG2_V39_ENTRY_MIN_PROCESSED_PNL_SOL="${PGG2_V39_ENTRY_MIN_PROCESSED_PNL_SOL:-0.00020}"
export PGG2_V39_BANK_PNL_SOL="${PGG2_V39_BANK_PNL_SOL:-0.00060}"
export PGG2_V39_SCRATCH_PNL_SOL="${PGG2_V39_SCRATCH_PNL_SOL:-0.00005}"
export PGG2_V39_CLAMP_LOSS_SOL="${PGG2_V39_CLAMP_LOSS_SOL:-0.00050}"
export PGG2_V39_MAX_HOLD_MS="${PGG2_V39_MAX_HOLD_MS:-3000}"
export PGG2_V39_ABSOLUTE_MAX_HOLD_MS="${PGG2_V39_ABSOLUTE_MAX_HOLD_MS:-5000}"
export PGG2_V39_MAX_SELL_LATENCY_MS="${PGG2_V39_MAX_SELL_LATENCY_MS:-750}"
export PGG2_V39_QUOTE_GRADIENT_MAX_DELAY_MS="${PGG2_V39_QUOTE_GRADIENT_MAX_DELAY_MS:-1500}"

export PGG2_V39_PREFETCH_INTERVAL_MS="${PGG2_V39_PREFETCH_INTERVAL_MS:-300}"
export PGG2_V39_PREFETCH_TTL_MS="${PGG2_V39_PREFETCH_TTL_MS:-500}"
export PGG2_V39_WATCHLIST_MAX_MS="${PGG2_V39_WATCHLIST_MAX_MS:-5000}"
export PGG2_V39_PREFETCH_AMOUNT_TOL_PCT="${PGG2_V39_PREFETCH_AMOUNT_TOL_PCT:-0.50}"
export PGG2_V39_PREFETCH_TRIGGER_ENTRY_ENABLED="${PGG2_V39_PREFETCH_TRIGGER_ENTRY_ENABLED:-1}"
export PGG2_V39_PREFETCH_BUY_QUOTE_MAX_AGE_MS="${PGG2_V39_PREFETCH_BUY_QUOTE_MAX_AGE_MS:-1500}"
export PGG2_V39_PREFETCH_TRIGGER_BUY_MAX_AGE_MS="${PGG2_V39_PREFETCH_TRIGGER_BUY_MAX_AGE_MS:-500}"
export PGG2_QUOTE_MGR_CACHE_TTL_MS="${PGG2_QUOTE_MGR_CACHE_TTL_MS:-500}"
export PGG2_QUOTE_MGR_REFRESH_AFTER_MS="${PGG2_QUOTE_MGR_REFRESH_AFTER_MS:-250}"
# Measured from the first live mirror: buy+sell tx cost averaged about
# 0.0000574 SOL roundtrip after excluding recoverable ATA rent.
export PGG2_V39_LIVE_ROUTE_AWARE_TX_FEE_SOL="${PGG2_V39_LIVE_ROUTE_AWARE_TX_FEE_SOL:-0.0000287}"
# v39 prepared-order mirror: send from the fresh quote-rescue snapshot. Do not
# force a late presend requote when a prepared order is fresh; the transaction
# min-token guard makes bad fills fail before opening a position.
export PGG2_V39_LIVE_REQUOTE_BEFORE_SEND="${PGG2_V39_LIVE_REQUOTE_BEFORE_SEND:-1}"
export PGG2_V39_PREPARED_ORDER_PIPELINE="${PGG2_V39_PREPARED_ORDER_PIPELINE:-1}"
export PGG2_V39_USE_PREPARED_ORDER_FOR_SEND="${PGG2_V39_USE_PREPARED_ORDER_FOR_SEND:-1}"
export PGG2_V39_PREPARED_SKIP_SIMULATE_BEFORE_SEND="${PGG2_V39_PREPARED_SKIP_SIMULATE_BEFORE_SEND:-1}"
export PGG2_V39_FAST_BUY_SEND="${PGG2_V39_FAST_BUY_SEND:-1}"
export PGG2_V39_SPECULATIVE_SELL_WORKER="${PGG2_V39_SPECULATIVE_SELL_WORKER:-0}"
export PGG2_V39_SELL_TRIGGER="${PGG2_V39_SELL_TRIGGER:-processed_or_token_balance}"
export PGG2_LIVE_MAX_FAILED_FEE_SPEND_SOL="${PGG2_LIVE_MAX_FAILED_FEE_SPEND_SOL:-0.00100}"
export PGG2_DRYLIVE_SPEC_SELL_MODEL="${PGG2_DRYLIVE_SPEC_SELL_MODEL:-1}"
export PGG2_V39_SPEC_SELL_MAX_ATTEMPTS="${PGG2_V39_SPEC_SELL_MAX_ATTEMPTS:-3}"
export PGG2_V39_SPEC_SELL_RETRY_MS="${PGG2_V39_SPEC_SELL_RETRY_MS:-150}"
export PGG2_V39_SPEC_SELL_POSTBUY_JOIN_MS="${PGG2_V39_SPEC_SELL_POSTBUY_JOIN_MS:-1200}"
export PGG2_V39_SPEC_SELL_MAX_FAILED_FEE_SOL="${PGG2_V39_SPEC_SELL_MAX_FAILED_FEE_SOL:-0.000060}"
export PGG2_V39_SPEC_SELL_MAX_FEE_EDGE_FRAC="${PGG2_V39_SPEC_SELL_MAX_FEE_EDGE_FRAC:-0.35}"
export PGG2_V39_PREPARED_BUY_MAX_AGE_MS="${PGG2_V39_PREPARED_BUY_MAX_AGE_MS:-350}"
export PGG2_V39_PREPARED_SELL_MAX_AGE_MS="${PGG2_V39_PREPARED_SELL_MAX_AGE_MS:-500}"
export PGG2_V39_PREPARED_BUY_BLOCKHASH_MAX_AGE_MS="${PGG2_V39_PREPARED_BUY_BLOCKHASH_MAX_AGE_MS:-30000}"
export PGG2_V39_LIVE_BUY_MAX_DRIFT_PCT="${PGG2_V39_LIVE_BUY_MAX_DRIFT_PCT:-2.0}"
export PGG2_V39_LIVE_BUY_MIN_DRIFT_PCT="${PGG2_V39_LIVE_BUY_MIN_DRIFT_PCT:-0.25}"
export PGG2_V39_LIVE_LANDED_PNL_FLOOR_SOL="${PGG2_V39_LIVE_LANDED_PNL_FLOOR_SOL:-0.00005}"
export PGG2_V39_LIVE_GATE_ON_MIN_LANDED_TOKENS="${PGG2_V39_LIVE_GATE_ON_MIN_LANDED_TOKENS:-1}"
export PGG2_V39_LANDED_PNL_ENTRY_GATE_ENABLED="${PGG2_V39_LANDED_PNL_ENTRY_GATE_ENABLED:-1}"
export PGG2_LIVE_ADAPTIVE_MIN_TOKEN_GUARD="${PGG2_LIVE_ADAPTIVE_MIN_TOKEN_GUARD:-1}"
export PGG2_LIVE_MIN_LANDED_PNL_SOL="${PGG2_LIVE_MIN_LANDED_PNL_SOL:-0.00005}"
export PGG2_LIVE_MIN_BUY_SLIPPAGE_PCT="${PGG2_LIVE_MIN_BUY_SLIPPAGE_PCT:-0.05}"
export PGG2_LIVE_MAX_BUY_SLIPPAGE_PCT="${PGG2_LIVE_MAX_BUY_SLIPPAGE_PCT:-0.80}"
export PGG2_LIVE_PRESEND_CONFIRM_DELAY_MS="${PGG2_LIVE_PRESEND_CONFIRM_DELAY_MS:-100}"
export PGG2_LIVE_MAX_EXPECTED_PNL_DECAY_SOL="${PGG2_LIVE_MAX_EXPECTED_PNL_DECAY_SOL:-0.00050}"
export PGG2_V39_LIVE_PRESEND_CONFIRM_ENABLED="${PGG2_V39_LIVE_PRESEND_CONFIRM_ENABLED:-1}"
export PGG2_V39_LIVE_PRESEND_CONFIRM_DELAY_MS="${PGG2_V39_LIVE_PRESEND_CONFIRM_DELAY_MS:-100}"
export PGG2_V39_LIVE_PRESEND_CONFIRM_FLOOR_SOL="${PGG2_V39_LIVE_PRESEND_CONFIRM_FLOOR_SOL:-0.00005}"
export PGG2_V39_LIVE_PRESEND_MAX_DECAY_SOL="${PGG2_V39_LIVE_PRESEND_MAX_DECAY_SOL:-0.00050}"
export PGG2_V39_LIVE_PROTECTED_SELL_MIN_OUT="${PGG2_V39_LIVE_PROTECTED_SELL_MIN_OUT:-1}"
export PGG2_V39_LIVE_SELL_MIN_ALL_IN_PNL_SOL="${PGG2_V39_LIVE_SELL_MIN_ALL_IN_PNL_SOL:-0.00000}"
export PGG2_V39_LIVE_PROTECTED_SELL_ALLOW_NEGATIVE_CLAMP="${PGG2_V39_LIVE_PROTECTED_SELL_ALLOW_NEGATIVE_CLAMP:-0}"
export PGG2_V39_LIVE_EMERGENCY_SELL_ON_HARD_LOSS="${PGG2_V39_LIVE_EMERGENCY_SELL_ON_HARD_LOSS:-1}"
export PGG2_V39_LIVE_EMERGENCY_CLOSE_LOSS_SOL="${PGG2_V39_LIVE_EMERGENCY_CLOSE_LOSS_SOL:-0.00100}"
export PGG2_V39_LIVE_EMERGENCY_CLOSE_MAX_HOLD_MS="${PGG2_V39_LIVE_EMERGENCY_CLOSE_MAX_HOLD_MS:-10000}"
export PGG2_V39_LIVE_EMERGENCY_MIN_SOL_OUT="${PGG2_V39_LIVE_EMERGENCY_MIN_SOL_OUT:-0.000000001}"
export PGG2_GLOBAL_SWAP_BUDGET_ENABLED="${PGG2_GLOBAL_SWAP_BUDGET_ENABLED:-1}"
export PGG2_GLOBAL_SWAP_MIN_INTERVAL_MS="${PGG2_GLOBAL_SWAP_MIN_INTERVAL_MS:-450}"
export PGG2_GLOBAL_SWAP_ENTRY_MIN_INTERVAL_MS="${PGG2_GLOBAL_SWAP_ENTRY_MIN_INTERVAL_MS:-0}"
export PGG2_GLOBAL_SWAP_ENTRY_MAX_WAIT_MS="${PGG2_GLOBAL_SWAP_ENTRY_MAX_WAIT_MS:-250}"
export PGG2_GLOBAL_SWAP_MAX_WAIT_MS="${PGG2_GLOBAL_SWAP_MAX_WAIT_MS:-900}"
export PGG2_GLOBAL_SWAP_DROP_BACKGROUND_ON_WAIT="${PGG2_GLOBAL_SWAP_DROP_BACKGROUND_ON_WAIT:-1}"
export PGG2_GLOBAL_SWAP_429_BACKOFF_MS="${PGG2_GLOBAL_SWAP_429_BACKOFF_MS:-2500}"
export PGG2_QUOTE_BUDGETER_ENABLED=1
export PGG2_QUOTE_BUDGET_MAX_QPS="${PGG2_QUOTE_BUDGET_MAX_QPS:-2.0}"
export PGG2_QUOTE_BUDGET_PREFETCH_QPS="${PGG2_QUOTE_BUDGET_PREFETCH_QPS:-0.5}"
export PGG2_QUOTE_BUDGET_BACKGROUND_QPS="${PGG2_QUOTE_BUDGET_BACKGROUND_QPS:-0.5}"
export PGG2_QUOTE_BUDGET_429_BACKOFF_MS="${PGG2_QUOTE_BUDGET_429_BACKOFF_MS:-1500}"

export PGG2_DRYLIVE_PILOT_ENABLED=0
export PGG2_SCALP_ENABLED=0
export PGG2_SHADOW_LAB_CANARY_ACTUAL_ENTRY=0
export PGG2_ENTRY_SNAPSHOT_BANK_ENABLED=0
export PGG2_ENTRY_SNAPSHOT_BANK_LIVE_ELIGIBLE=0

export PGG2_SHADOW_LAB_ENABLED=1
export PGG2_SHADOW_OBSERVE_ENABLED=1
export PGG2_SHADOW_LAB_MAX_CONCURRENT="${PGG2_SHADOW_LAB_MAX_CONCURRENT:-8}"
export PGG2_SHADOW_LAB_COOLDOWN_MS="${PGG2_SHADOW_LAB_COOLDOWN_MS:-12000}"
export PGG2_SHADOW_OBSERVE_MIN_SOL_V39_LEAD="${PGG2_SHADOW_OBSERVE_MIN_SOL_V39_LEAD:-0.0}"
export PGG2_SHADOW_LAB_SELL_DELAYS_MS="${PGG2_SHADOW_LAB_SELL_DELAYS_MS:-}"
export PGG2_SHADOW_DELAYED_ENTRY_SCANNER=0
export PGG2_V39_LEAD_MIN_BUY_SOL_700="${PGG2_V39_LEAD_MIN_BUY_SOL_700:-0.70}"
export PGG2_V39_LEAD_MIN_BUYERS_700="${PGG2_V39_LEAD_MIN_BUYERS_700:-1}"
export PGG2_V39_LEAD_MAX_TOP_SHARE_700="${PGG2_V39_LEAD_MAX_TOP_SHARE_700:-1.0}"
export PGG2_V39_LEAD_MAX_SELL_RATIO_700="${PGG2_V39_LEAD_MAX_SELL_RATIO_700:-0.35}"

export PGG2_RISK_WORKER_ENABLED=1
export PGG2_RISK_WORKER_OWNS_QUOTE_EXIT=1
export PGG2_RISK_ALLOW_OVERLAP_QUOTES=0

export PGG2_LIVE_BUY_SLIPPAGE_PCT="${PGG2_LIVE_BUY_SLIPPAGE_PCT:-65}"
export PGG2_LIVE_SELL_SLIPPAGE_PCT="${PGG2_LIVE_SELL_SLIPPAGE_PCT:-99}"
export PGG2_LIVE_MAX_TRADE_SOL="${PGG2_LIVE_MAX_TRADE_SOL:-0.015}"
export PGG2_LIVE_MIN_TRADE_SOL="${PGG2_LIVE_MIN_TRADE_SOL:-0.015}"
export PGG2_LIVE_MIN_WALLET_RESERVE_SOL="${PGG2_LIVE_MIN_WALLET_RESERVE_SOL:-0.080}"
export PGG2_LIVE_MAX_SESSION_LOSS_SOL=999
export PGG2_LIVE_MAX_CONSECUTIVE_LOSSES=999

echo "PGG2-LIVE-MIRROR-START run_prefix=${PGG2_RUN_PREFIX} target_entries=${PGG2_V39_TARGET_ENTRIES} max_open=${PGG2_V39_MAX_OPEN} route=pump_bc sim_needed_required=0 send_mode=${PGG2_LIVE_SEND_MODE} jito=${PGG2_JITO_ENABLED} jito_submit_method=${PGG2_JITO_SUBMIT_METHOD} protected_hold=0 old_esb=0"
exec ./start_pgg2_attack_paper.sh
