#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# Dry-live mirror of start_pgg2_direct_live_candidate.sh.
# Same strategy config and direct Pump/PumpSwap builder, but quote mode keeps
# send=0 so no real SOL can move. Quote-shadow positions use direct quotes and
# the live cost model from start_pgg2_attack_paper.sh.

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_direct_drylive_rules}"
export PGG2_EXECUTION_MODE=quote
export PGG2_ENABLE_LIVE=1
export PIGGY_PAPER_TRADING=0
export PGG2_DRY_LIVE_MODE=1
export PGG2_LIVE_BROKER=direct_pump
export PGG2_WALLET_KEYPAIR="${PGG2_WALLET_KEYPAIR:-/root/piggy/live_wallet.key}"

# Match live timing: build direct Pump/PumpSwap quotes locally, do not add a
# simulate/preflight round trip before a dry-live entry.
export PGG2_QUOTE_SHADOW_POSITIONS=1
export PGG2_QUOTE_SIMULATE=0
export PGG2_LIVE_SIMULATE_BEFORE_SEND=0
export PGG2_LIVE_SKIP_PREFLIGHT=1
export PGG2_LIVE_PREFLIGHT_ROUNDTRIP_ENABLED=0
export PGG2_LIVE_FINAL_ENTRY_GUARD_ENABLED=0
export PGG2_DIRECT_SELECT_BUYBACK_BY_SIM=0
export PGG2_DIRECT_REQUIRE_SIM_SELECTED_BUYBACK=0
export PGG2_DIRECT_OBSERVED_PAIR_FROM_RAW=1
export PGG2_DIRECT_OBSERVED_PAIR_MAX_SIGS="${PGG2_DIRECT_OBSERVED_PAIR_MAX_SIGS:-10}"
export PGG2_DIRECT_OBSERVED_PAIR_TAIL_BYTES="${PGG2_DIRECT_OBSERVED_PAIR_TAIL_BYTES:-8388608}"
export PGG2_DIRECT_PUMP_REMAINING_CACHE="${PGG2_DIRECT_PUMP_REMAINING_CACHE:-/root/piggy/data/pgg2_pump_remaining_cache.json}"
export PGG2_DIRECT_REQUIRE_OBSERVED_BUYBACK_PAIR=1
export PGG2_DIRECT_ACCOUNT_COMMITMENT=processed
export PGG2_DIRECT_BLOCKHASH_COMMITMENT=processed
export PGG2_DIRECT_CURVE_ACCOUNT_TTL_SEC=0

# Keep the current production-candidate live profile. The only strategy change
# in this run is the validated loss-cutter below.
export PGG2_PRICED_SNAP_MIN_BUY1500="${PGG2_PRICED_SNAP_MIN_BUY1500:-7.0}"
export PGG2_PRICED_SNAP_MIN_UNIQ1500="${PGG2_PRICED_SNAP_MIN_UNIQ1500:-8}"
export PGG2_PRICED_SNAP_MAX_TOP1500="${PGG2_PRICED_SNAP_MAX_TOP1500:-0.37}"
export PGG2_PRICED_SNAP_MAX_AGE_SEC="${PGG2_PRICED_SNAP_MAX_AGE_SEC:-12.0}"
export PGG2_PRICED_SNAP_STANDARD_ENTRY_FRACTION="${PGG2_PRICED_SNAP_STANDARD_ENTRY_FRACTION:-0.30}"
export PGG2_PRICED_SNAP_ELITE_ENTRY_FRACTION="${PGG2_PRICED_SNAP_ELITE_ENTRY_FRACTION:-0.80}"
export PGG2_PRICED_SNAP_ELITE_MIN_BUY1500="${PGG2_PRICED_SNAP_ELITE_MIN_BUY1500:-12.0}"
export PGG2_PRICED_SNAP_ELITE_MIN_UNIQ1500="${PGG2_PRICED_SNAP_ELITE_MIN_UNIQ1500:-10}"
export PGG2_PRICED_SNAP_ELITE_MAX_TOP1500="${PGG2_PRICED_SNAP_ELITE_MAX_TOP1500:-0.30}"
export PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC="${PGG2_PRICED_SNAP_ELITE_MAX_AGE_SEC:-12.0}"
export PGG2_PRICED_SNAP_ELITE_MAX_SLOT_TOP="${PGG2_PRICED_SNAP_ELITE_MAX_SLOT_TOP:-0.60}"
export PGG2_PRICED_SNAP_TOXIC_TOP_LOSSCUT_ENABLED="${PGG2_PRICED_SNAP_TOXIC_TOP_LOSSCUT_ENABLED:-1}"
export PGG2_PRICED_SNAP_TOXIC_TOP_MAX_TOP1500="${PGG2_PRICED_SNAP_TOXIC_TOP_MAX_TOP1500:-0.365}"
export PGG2_PRICED_SNAP_THIN_DELAYED_CONCENTRATION_SKIP_ENABLED="${PGG2_PRICED_SNAP_THIN_DELAYED_CONCENTRATION_SKIP_ENABLED:-1}"
export PGG2_PRICED_SNAP_THIN_DELAYED_MIN_TOP1500="${PGG2_PRICED_SNAP_THIN_DELAYED_MIN_TOP1500:-0.30}"
export PGG2_PRICED_SNAP_THIN_DELAYED_MAX_TOP1500="${PGG2_PRICED_SNAP_THIN_DELAYED_MAX_TOP1500:-0.365}"
export PGG2_PRICED_SNAP_THIN_DELAYED_MIN_ENTRY_MOVE="${PGG2_PRICED_SNAP_THIN_DELAYED_MIN_ENTRY_MOVE:-1.18}"
export PGG2_PRICED_SNAP_THIN_DELAYED_MAX_ENTRY_MOVE="${PGG2_PRICED_SNAP_THIN_DELAYED_MAX_ENTRY_MOVE:-1.30}"
export PGG2_PRICED_SNAP_THIN_DELAYED_MIN_BUY1500="${PGG2_PRICED_SNAP_THIN_DELAYED_MIN_BUY1500:-8.0}"

# Live-derived surgical loss cutter. On the gold direct-live run it would have
# skipped 8 losses and 0 winners across priced_snap + curve_lag_reveal.
export PGG2_LIVE_LOSS_CUTTER_ENABLED="${PGG2_LIVE_LOSS_CUTTER_ENABLED:-1}"
export PGG2_LIVE_LOSSCUT_MIN_UNIQ1500="${PGG2_LIVE_LOSSCUT_MIN_UNIQ1500:-6}"
export PGG2_LIVE_LOSSCUT_LOW_BUY1500="${PGG2_LIVE_LOSSCUT_LOW_BUY1500:-10.5}"
export PGG2_LIVE_LOSSCUT_LOW_SCORE="${PGG2_LIVE_LOSSCUT_LOW_SCORE:-150}"

# Exit-side recovery protections found in the current dry-live run. These do
# not block entries. They only stop premature loss exits on profiles that later
# recovered into executable winners.
export PGG2_CURVE_LAG_BROAD_QUOTE_GRACE_ENABLED="${PGG2_CURVE_LAG_BROAD_QUOTE_GRACE_ENABLED:-1}"
export PGG2_CURVE_LAG_BROAD_QUOTE_GRACE_SEC="${PGG2_CURVE_LAG_BROAD_QUOTE_GRACE_SEC:-4.25}"
export PGG2_CURVE_LAG_BROAD_GRACE_MIN_BUY1500="${PGG2_CURVE_LAG_BROAD_GRACE_MIN_BUY1500:-18.0}"
export PGG2_CURVE_LAG_BROAD_GRACE_MIN_UNIQ1500="${PGG2_CURVE_LAG_BROAD_GRACE_MIN_UNIQ1500:-12}"
export PGG2_CURVE_LAG_BROAD_GRACE_MAX_TOP1500="${PGG2_CURVE_LAG_BROAD_GRACE_MAX_TOP1500:-0.20}"
export PGG2_CURVE_LAG_BROAD_GRACE_MIN_LIVE_BUY700="${PGG2_CURVE_LAG_BROAD_GRACE_MIN_LIVE_BUY700:-8.0}"
export PGG2_CURVE_LAG_BROAD_GRACE_MIN_LIVE_UNIQ700="${PGG2_CURVE_LAG_BROAD_GRACE_MIN_LIVE_UNIQ700:-5}"
export PGG2_CURVE_LAG_BROAD_GRACE_MAX_LIVE_TOP700="${PGG2_CURVE_LAG_BROAD_GRACE_MAX_LIVE_TOP700:-0.35}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_GRACE_ENABLED="${PGG2_PRICED_SNAP_STRONG_FOLLOW_GRACE_ENABLED:-1}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_GRACE_SEC="${PGG2_PRICED_SNAP_STRONG_FOLLOW_GRACE_SEC:-75.0}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_MAX_ENTRY_MOVE="${PGG2_PRICED_SNAP_STRONG_FOLLOW_MAX_ENTRY_MOVE:-1.30}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_WINDOW_MS="${PGG2_PRICED_SNAP_STRONG_FOLLOW_WINDOW_MS:-3000}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_MIN_BUY_SOL="${PGG2_PRICED_SNAP_STRONG_FOLLOW_MIN_BUY_SOL:-7.5}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_MIN_BUYERS="${PGG2_PRICED_SNAP_STRONG_FOLLOW_MIN_BUYERS:-10}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_MAX_TOP="${PGG2_PRICED_SNAP_STRONG_FOLLOW_MAX_TOP:-0.60}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_MAX_SELL_RATIO700="${PGG2_PRICED_SNAP_STRONG_FOLLOW_MAX_SELL_RATIO700:-0.04}"
export PGG2_PRICED_SNAP_STRONG_FOLLOW_MAX_LAST_BUY_MS="${PGG2_PRICED_SNAP_STRONG_FOLLOW_MAX_LAST_BUY_MS:-350}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_GRACE_ENABLED="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_GRACE_ENABLED:-1}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_GRACE_SEC="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_GRACE_SEC:-14.0}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_PANIC_MULT="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_PANIC_MULT:-0.72}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_ENTRY_MOVE="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_ENTRY_MOVE:-1.18}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_ENTRY_MOVE="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_ENTRY_MOVE:-1.30}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_BUY1500="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_BUY1500:-7.5}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_UNIQ1500="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_UNIQ1500:-8}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_TOP1500="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_TOP1500:-0.30}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_ENTRY_SELL_RATIO="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_ENTRY_SELL_RATIO:-0.01}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_WINDOW_MS="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_WINDOW_MS:-700}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_FOLLOW_BUY_SOL="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_FOLLOW_BUY_SOL:-8.0}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_FOLLOW_BUYERS="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MIN_FOLLOW_BUYERS:-12}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_FOLLOW_TOP="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_FOLLOW_TOP:-0.50}"
export PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_FOLLOW_SELL_RATIO="${PGG2_PRICED_SNAP_DELAYED_RUNWAY_MAX_FOLLOW_SELL_RATIO:-0.06}"
export PGG2_PRICED_SNAP_POST_OPEN_LOSS_CUT_ENABLED="${PGG2_PRICED_SNAP_POST_OPEN_LOSS_CUT_ENABLED:-1}"
export PGG2_PRICED_SNAP_POST_OPEN_LOSS_CUT_UNTIL_SEC="${PGG2_PRICED_SNAP_POST_OPEN_LOSS_CUT_UNTIL_SEC:-4.0}"
export PGG2_PRICED_SNAP_POST_OPEN_LOSS_CUT_MAX_PEAK="${PGG2_PRICED_SNAP_POST_OPEN_LOSS_CUT_MAX_PEAK:-1.18}"
export PGG2_PRICED_SNAP_POST_OPEN_LOSS_CUT_WINDOW_MS="${PGG2_PRICED_SNAP_POST_OPEN_LOSS_CUT_WINDOW_MS:-700}"
export PGG2_PRICED_SNAP_POST_OPEN_DIST_MIN_AGE_SEC="${PGG2_PRICED_SNAP_POST_OPEN_DIST_MIN_AGE_SEC:-0.70}"
export PGG2_PRICED_SNAP_POST_OPEN_DIST_MIN_SELL_SOL="${PGG2_PRICED_SNAP_POST_OPEN_DIST_MIN_SELL_SOL:-1.0}"
export PGG2_PRICED_SNAP_POST_OPEN_DIST_MIN_SELL_RATIO="${PGG2_PRICED_SNAP_POST_OPEN_DIST_MIN_SELL_RATIO:-0.20}"
export PGG2_PRICED_SNAP_ZERO_FOLLOW_MIN_AGE_SEC="${PGG2_PRICED_SNAP_ZERO_FOLLOW_MIN_AGE_SEC:-0.55}"
export PGG2_PRICED_SNAP_ZERO_FOLLOW_MAX_BUY_SOL="${PGG2_PRICED_SNAP_ZERO_FOLLOW_MAX_BUY_SOL:-0.20}"
export PGG2_PRICED_SNAP_ZERO_FOLLOW_MIN_SELL_SOL="${PGG2_PRICED_SNAP_ZERO_FOLLOW_MIN_SELL_SOL:-0.02}"
export PGG2_PRICED_SNAP_ZERO_FOLLOW_MAX_MULT="${PGG2_PRICED_SNAP_ZERO_FOLLOW_MAX_MULT:-0.90}"

# Same executable tolerances as the direct live candidate; quote mode uses these
# to build the exact same route shape while never sending it.
export PGG2_LIVE_BUY_SLIPPAGE_PCT="${PGG2_LIVE_BUY_SLIPPAGE_PCT:-65}"
export PGG2_LIVE_SELL_SLIPPAGE_PCT="${PGG2_LIVE_SELL_SLIPPAGE_PCT:-99}"
export PGG2_DIRECT_EXIT_ANY_EXECUTABLE_PRICE=1
export PGG2_DIRECT_EXIT_MIN_LAMPORTS=1

export PGG2_LIVE_MAX_TRADE_SOL="${PGG2_LIVE_MAX_TRADE_SOL:-0.050}"
export PGG2_LIVE_MIN_TRADE_SOL="${PGG2_LIVE_MIN_TRADE_SOL:-0.015}"
export PGG2_LIVE_MIN_WALLET_RESERVE_SOL="${PGG2_LIVE_MIN_WALLET_RESERVE_SOL:-0.080}"
export PGG2_LIVE_MAX_SESSION_LOSS_SOL="${PGG2_LIVE_MAX_SESSION_LOSS_SOL:-999}"
export PGG2_LIVE_MAX_CONSECUTIVE_LOSSES="${PGG2_LIVE_MAX_CONSECUTIVE_LOSSES:-999}"

export PGG2_LIVE_HTTP_RETRIES="${PGG2_LIVE_HTTP_RETRIES:-2}"
export PGG2_LIVE_HTTP_RETRY_BASE_SEC="${PGG2_LIVE_HTTP_RETRY_BASE_SEC:-0.25}"

exec ./start_pgg2_attack_paper.sh
