#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy
RUNID="pgg2_live_paperwin_$(date -u +%Y%m%d_%H%M%S)"
echo "$RUNID" > /root/piggy/current_pgg2_runid.txt

export PGG2_EXECUTION_MODE=live
export PGG2_ENABLE_LIVE=1
export PGG2_LIVE_CONFIRM=I_ACCEPT_REAL_SOL_RISK
export PIGGY_PAPER_TRADING=0

export PGG2_WALLET_KEYPAIR="${PGG2_WALLET_KEYPAIR:-/root/piggy/live_wallet.key}"

# Mirrors the winning pgg2_artgate_hetzner_20260505_135326 paper config.
export PIGGY_NO_FOLLOW_CAP_ON=1
export PIGGY_MOON_HARD_BREAK_MULT=0.88
export PIGGY_MAX_OPEN_POSITIONS=3
export PIGGY_SCOUT_SOL=0.020
export PIGGY_MAX_POSITION_SOL=0.200

export PGG2_BIRTH_FANOUT_ENABLED=1
export PGG2_BIRTH_FANOUT_SCALE_ENABLED=0
export PGG2_BIRTH_FANOUT_MIN_LIVE_BUYERS700=7
export PGG2_BIRTH_FANOUT_MAX_LIVE_TOP700=0.62
export PGG2_REJECT_LATE_WHALE_DRAG=1
export PGG2_SCALE_MIN_ENTRY_UNIQ700=4
export PGG2_SCALE_MAX_ENTRY_TOP700=0.55
export PGG2_SECOND_WAVE_FORCE_SCOUT=1
export PGG2_SECOND_WAVE_MAX_SCOUT_SOL=0.020
export PGG2_CURVE_LAG_REVEAL_ENABLED=1
export PGG2_CURVE_LAG_SOL=0.020
export PGG2_CURVE_LAG_MIN_LIVE_BUY700_SOL=5.0
export PGG2_CURVE_LAG_MIN_LIVE_BUYERS700=5
export PGG2_CURVE_LAG_MAX_LIVE_TOP700=0.70
export PGG2_CURVE_LAG_MAX_ENTRY_MOVE=1.25
export PGG2_PROFIT_REENTRY_LOCK_MIN_PNL_SOL=0.001

# Live execution safety: same signal sizing, but no sub-paper-size trades.
export PGG2_LIVE_MAX_TRADE_SOL=0.020
export PGG2_LIVE_MIN_TRADE_SOL=0.010
export PGG2_LIVE_BIRTH_FANOUT_MAX_TRADE_SOL=0.010
export PGG2_LIVE_BIRTH_FANOUT_MIN_TRADE_SOL=0.005
export PGG2_LIVE_IGNITION_MAX_TRADE_SOL=0.020
export PGG2_LIVE_IGNITION_MIN_TRADE_SOL=0.010
export PGG2_LIVE_CURVE_LAG_FULL_MAX_WAVE_BASE_MOVE=0.90
export PGG2_LIVE_FLAT_CURVE_LAG_MAX_TRADE_SOL=0.010
export PGG2_LIVE_FLAT_CURVE_LAG_MIN_TRADE_SOL=0.005
export PGG2_LIVE_SECOND_WAVE_FULL_MIN_BUY700=5.0
export PGG2_LIVE_SECOND_WAVE_FULL_MIN_UNIQ700=4
export PGG2_LIVE_SECOND_WAVE_FULL_MAX_TOP700=0.62
export PGG2_LIVE_WEAK_SECOND_WAVE_MAX_TRADE_SOL=0.010
export PGG2_LIVE_WEAK_SECOND_WAVE_MIN_TRADE_SOL=0.005
export PGG2_LIVE_EDGE_FILTER_ENABLED=1
export PGG2_LIVE_EDGE_BIRTH_MIN_UNIQ1500=14
export PGG2_LIVE_EDGE_BIRTH_HARD_MIN_BUY1500=14.0
export PGG2_LIVE_EDGE_BIRTH_MIN_SCORE=230
export PGG2_LIVE_EDGE_BIRTH_MIN_BUY1500=15.5
export PGG2_LIVE_EDGE_BIRTH_MAX_TOP1500=0.30
export PGG2_LIVE_EDGE_CURVE_STRONG_TOP700=0.50
export PGG2_LIVE_EDGE_CURVE_LOW_VSOL_MIN_TOP700=0.3458
export PGG2_LIVE_EDGE_CURVE_LOW_VSOL_MAX=35.0
export PGG2_LIVE_EDGE_CURVE_BOOTSTRAP_MAX_SCORE=100
export PGG2_LIVE_EDGE_CURVE_BOOTSTRAP_MIN_BUY1500=17.5
export PGG2_LIVE_EDGE_CURVE_BOOTSTRAP_MAX_VSOL=35.0
export PGG2_LIVE_EDGE_CURVE_BOOTSTRAP_MAX_VSOL_STRICT=38.0
export PGG2_LIVE_EDGE_CURVE_MIN_MOVE700=0.98
export PGG2_LIVE_EDGE_BREADTH_MIN_SCORE=140
export PGG2_LIVE_EDGE_BREADTH_MIN_BUY1500=3.0
export PGG2_LIVE_EDGE_BREADTH_MIN_UNIQ1500=8
export PGG2_LIVE_EDGE_BREADTH_MIN_MOVE700=1.05
export PGG2_LIVE_EDGE_BREADTH_MIN_VSOL=40.0
export PGG2_LIVE_EDGE_BREADTH_MIN_SLOT_BUYERS=5
export PGG2_LIVE_EDGE_BREADTH_MAX_SLOT_TOP=0.35
export PGG2_LIVE_EDGE_RECLAIM_MIN_UNIQ700=7
export PGG2_LIVE_EDGE_RECLAIM_MAX_TOP700=0.32
export PGG2_LIVE_EDGE_SECOND_MIN_UNIQ1500=8
export PGG2_LIVE_EDGE_SECOND_MAX_TOP700=0.40
export PGG2_LIVE_EDGE_IGNITION_MIN_SCORE=190
export PGG2_LIVE_EDGE_IGNITION_MIN_BUY1500=6.0
export PGG2_LIVE_MIN_WALLET_RESERVE_SOL=0.020
export PGG2_LIVE_MAX_SESSION_LOSS_SOL=0.025
export PGG2_LIVE_MAX_CONSECUTIVE_LOSSES=2
export PGG2_LIVE_PRIORITY_FEE=auto
export PGG2_LIVE_PRIORITY_LEVEL=high
export PGG2_LIVE_BUY_SLIPPAGE_PCT=18
export PGG2_LIVE_SELL_SLIPPAGE_PCT=22
export PGG2_LIVE_TX_VERSION=legacy
# Paper did not do an extra RPC simulation before entry. Keep live execution fast
# and let sendTransaction's normal preflight handle invalid transactions.
export PGG2_LIVE_SIMULATE_BEFORE_SEND=0
# Enter management immediately after buy sendTransaction, matching paper timing.
# Sells still use exact wallet delta and refuse false profit exits.
export PGG2_LIVE_FAST_PAPER_ACCOUNTING=1
export PGG2_LIVE_MIN_PROFIT_EXIT_SOL=0.00235
export PGG2_LIVE_RPC_URL="${PGG2_LIVE_RPC_URL:-https://api.mainnet-beta.solana.com}"

export PIGGY_STATE_FILE="/root/piggy/data/${RUNID}_state.json"
export PIGGY_RAW_EVENTS_FILE="/root/piggy/data/${RUNID}_raw.jsonl"
export PIGGY_DECISIONS_FILE="/root/piggy/data/${RUNID}_decisions.jsonl"

exec ./venv/bin/python -u PGG2.py 2>&1 | tee "/root/piggy/logs/${RUNID}.log"
