#!/usr/bin/env bash
set -euo pipefail

cd /root/piggy

# Phase 4 2026-05-08 dry-live wrapper.
# Adds moonshot-rider on top of Phase 2A + Phase 3:
# - Latch ride-mode when peak >= 1.30 within 30s of open
# - Tiered trail (0.40/0.50/0.70/0.85 by peak height)
# - Bypasses quote_profit_bank, quote_loss_clamp, scout_profit_protect when latched
# - Backtest on 22 live runs: +$132.96 net delta vs actual (13x improvement)

export PGG2_RUN_PREFIX="${PGG2_RUN_PREFIX:-pgg2_phase4_drylive}"

# Phase 2A — adaptive guards + filter pruning
export PGG2_PRICED_SNAP_BLOCK_TOP700=1.01
export PGG2_LIVE_BLOCK_HHI700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE700_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_MOVE1500_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_PER_BUYER_ABOVE=99999
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_BELOW=-1
export PGG2_PRICED_SNAP_BLOCK_AVG_BUY_7_TIGHT=-1
export PGG2_PRICED_SNAP_BLOCK_SCORE_BELOW=0
export PGG2_BLOCK_HOURS_UTC="${PGG2_BLOCK_HOURS_UTC:-18,19,20}"
export PGG2_CIRCUIT_BREAKER_LOSSES="${PGG2_CIRCUIT_BREAKER_LOSSES:-5}"
export PGG2_CIRCUIT_BREAKER_PAUSE_SEC="${PGG2_CIRCUIT_BREAKER_PAUSE_SEC:-300}"

# Phase 3 — keep PEAK-LOCK + hard_break gate (active for non-latched trades)
# curve_lag_reveal STAYS ENABLED for Phase 4 — backtest showed many of its
# quote_loss_clamp losers actually hit moonshot peaks; the moonshot-rider
# converts those into wins. Disabling the lane outright would lose those.
export PGG2_CURVE_LAG_REVEAL_ENABLED="${PGG2_CURVE_LAG_REVEAL_ENABLED:-1}"
export PGG2_PEAK_LOCK_ENABLED="${PGG2_PEAK_LOCK_ENABLED:-1}"
export PGG2_PEAK_LOCK_LOW_PEAK="${PGG2_PEAK_LOCK_LOW_PEAK:-1.18}"
export PGG2_PEAK_LOCK_LOW_FLOOR="${PGG2_PEAK_LOCK_LOW_FLOOR:-1.05}"
export PGG2_PEAK_LOCK_LOW_TRAIL="${PGG2_PEAK_LOCK_LOW_TRAIL:-0.92}"
export PGG2_PEAK_LOCK_MID_PEAK="${PGG2_PEAK_LOCK_MID_PEAK:-1.30}"
export PGG2_PEAK_LOCK_MID_FLOOR="${PGG2_PEAK_LOCK_MID_FLOOR:-1.15}"
export PGG2_PEAK_LOCK_MID_TRAIL="${PGG2_PEAK_LOCK_MID_TRAIL:-0.88}"
export PGG2_PEAK_LOCK_HIGH_PEAK="${PGG2_PEAK_LOCK_HIGH_PEAK:-1.60}"
export PGG2_PEAK_LOCK_HIGH_FLOOR="${PGG2_PEAK_LOCK_HIGH_FLOOR:-1.30}"
export PGG2_PEAK_LOCK_HIGH_TRAIL="${PGG2_PEAK_LOCK_HIGH_TRAIL:-0.85}"
export PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW="${PGG2_HARD_BREAK_REQUIRE_PEAK_BELOW:-1.18}"
export PGG2_ANTI_MARTINGALE_ENABLED="${PGG2_ANTI_MARTINGALE_ENABLED:-1}"
export PGG2_ANTI_MARTINGALE_LOSS_STREAK="${PGG2_ANTI_MARTINGALE_LOSS_STREAK:-2}"
export PGG2_ANTI_MARTINGALE_LOSS_SCALE="${PGG2_ANTI_MARTINGALE_LOSS_SCALE:-0.50}"
export PGG2_ANTI_MARTINGALE_WIN_STREAK="${PGG2_ANTI_MARTINGALE_WIN_STREAK:-2}"
export PGG2_ANTI_MARTINGALE_WIN_SCALE="${PGG2_ANTI_MARTINGALE_WIN_SCALE:-1.30}"

# Phase 4 — MOONSHOT-RIDER
export PGG2_MOONSHOT_RIDE_ENABLED="${PGG2_MOONSHOT_RIDE_ENABLED:-1}"
export PGG2_MOONSHOT_RIDE_PEAK="${PGG2_MOONSHOT_RIDE_PEAK:-1.30}"
export PGG2_MOONSHOT_RIDE_WINDOW_SEC="${PGG2_MOONSHOT_RIDE_WINDOW_SEC:-30.0}"
export PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC="${PGG2_MOONSHOT_RIDE_HARD_TIMEOUT_SEC:-90.0}"
export PGG2_MOONSHOT_RIDE_TIER0_TRAIL="${PGG2_MOONSHOT_RIDE_TIER0_TRAIL:-0.85}"
export PGG2_MOONSHOT_RIDE_TIER1_PEAK="${PGG2_MOONSHOT_RIDE_TIER1_PEAK:-1.60}"
export PGG2_MOONSHOT_RIDE_TIER1_TRAIL="${PGG2_MOONSHOT_RIDE_TIER1_TRAIL:-0.70}"
export PGG2_MOONSHOT_RIDE_TIER2_PEAK="${PGG2_MOONSHOT_RIDE_TIER2_PEAK:-2.00}"
export PGG2_MOONSHOT_RIDE_TIER2_TRAIL="${PGG2_MOONSHOT_RIDE_TIER2_TRAIL:-0.50}"
export PGG2_MOONSHOT_RIDE_TIER3_PEAK="${PGG2_MOONSHOT_RIDE_TIER3_PEAK:-3.00}"
export PGG2_MOONSHOT_RIDE_TIER3_TRAIL="${PGG2_MOONSHOT_RIDE_TIER3_TRAIL:-0.40}"

exec ./start_pgg2_direct_drylive_candidate.sh
